### ISSUE TITLE
Running tests in container

### ISSUE THREAD

**Issue by Trojan295** [Kong/docker-kong#105]
Hello,

I'm building a Kong plugin and trying to run integrations tests in a Docker container. I'm trying to use this Docker image, but some problems occur.

Basically I have a Dockerfile, which uses this one. In addition it installs some Lua dependencies required by my plugin, sets the environment variables required to connect to Cassandra (which is also running in a container), clones the Kong repository inside it and adds my plugin sources.

But when running tests it freezes. I'm aware, that `KONG_NGINX_DAEMON` is by default set to off and I set this to on. I confirmed this is ok, cause when running `./bin/kong start` it goes to the background and Kong is running.

Looks in case I run `./bin/busted` and use `helpers.start_kong()` in my tests, it still causes to run Kong in foreground and my tests are blocked. Is it not honoring the `KONG_NGINX_DAEMON` variable? Was someone successful in running integration tests inside a container?

**Comment by hutchic** [comment]
https://github.com/Kong/kong-vagrant is a more suitable way to develop / test Kong.

A development focused Dockerfile could be useful if you'd like to PR one to https://github.com/Kong/kong
