### ISSUE TITLE
Issue with logs option when start Kong

### ISSUE THREAD

**Issue by trunglh88** [Kong/docker-kong#110]
I install follow https://getkong.org/install/docker/ but when start Kong i have error :
```
nginx: [emerg] invalid log level "Files/Git/dev/stderr" in /usr/local/kong/nginx.conf:5
```
when i remove all options : 
```
"KONG_PROXY_ACCESS_LOG=/dev/stdout"
"KONG_ADMIN_ACCESS_LOG=/dev/stdout"
"KONG_PROXY_ERROR_LOG=/dev/stderr"
"KONG_ADMIN_ERROR_LOG=/dev/stderr"
```
then Kong start success
is this bug ?

i using 
- Docker Version 17.06.2-ce-win27 (13194)
- Kong : 0.11.0

**Comment by p0pr0ck5** [comment]
I suspect this is an issue with Windows; similar issues have been reported with pathing in Kong in particularly (admittedly with Vagrant, not Docker): https://github.com/Mashape/kong/issues/2458

Kong/OpenResty is not supported on Windows. Even if Docker does run on Windows, I suspect that underlying problems with Docker representation of streams like stdout/stderr are responsible here. In this case, logging can still be handled via any number of logging plugins available to Kong: https://getkong.org/plugins/

**Comment by thomasOBrian** [comment]
@p0pr0ck5 - you should really add that kong does not work on docker for windows -> https://docs.konghq.com/install/docker/?_ga=2.264864335.1525221271.1532618338-1922410801.1532618338

**Comment by gszr** [comment]
Is this still the case with newer versions of Docker for Windows? Please feel free to reopen if so, closing this for now, as there hasn't been activity in over two years.
