### ISSUE TITLE
Kong visibility

### ISSUE THREAD

**Issue by Niradnik** [Kong/docker-kong#115]
Hey I read everywhere that to communicate 2 containers have to be in the same network, and it give me a problem.
I have kong inside a container and I want to add api from other servers so is it possible in the case of non-dockerized api and in the case of dokerized one ?
My issue is if 2 container have to be part of the same docker network to communicate how can I make containers on different physical server to communicate

**Comment by cilindrox** [comment]
@Niradnik take a look at [docker-compose](https://docs.docker.com/compose/overview/) that'll allow you to run all of your containers on the same network with the added bonus of being a dev-focused tool.

Alternatively, you could start all your containers with the same `--network`

**Comment by hutchic** [comment]
this old issue hasn't seen any recent updates. If the problem is still present feel free to ping
