### ISSUE TITLE
Kong - External Postgres - Support _FILE for secret passing

### ISSUE THREAD

**Issue by knoxv1lle** [Kong/docker-kong#121]
GIVEN I have a kong container
and the environment variable KONG_PG_PASSWORD**_FILE** is set to a secret file
WHEN Docker is run 
THEN  KONG_PG_PASSWORD should be set to the value in the mounted secret file

**Comment by hutchic** [comment]
I think [docker secret](https://docs.docker.com/engine/reference/commandline/secret/) should achieve what you're trying for here or in lieu of that there's always consul-vault. Regardless at this time I don't see us implementing this functionality.
