### ISSUE TITLE
Error after executing docker-compose up -d

### ISSUE THREAD

**Issue by santteegt** [Kong/docker-kong#122]
After trying to build docker compose, the kong container is not up and shows the following error in console:

```
database 'kong' is missing migration
```

I'm working with the 0.11.1 release version of the repo.

**Comment by sas05** [comment]
I also have same error 

`
kong_1            | 2017/11/03 08:44:20 [warn] postgres database 'kong' is missing migration: (response-transformer) 2016-05-04-160000_resp_trans_schema_changes
kong_1            | Error: /usr/local/share/lua/5.1/kong/cmd/start.lua:28: [postgres error] the current database schema does not match this version of Kong. Please run `kong migrations up` to update/initialize the database schema. Be aware that Kong migrations should only run from a single node, and that nodes running migrations concurrently will conflict with each other and might corrupt your database schema!
kong_1            |
kong_1            |   Run with --v (verbose) or --vv (debug) for more details
kong_1            | prefix directory /usr/local/kong not found, trying to create it
compose_kong_1 exited with code 1
`

**Comment by woodpig07** [comment]
I got the similar `missing migration` issue when run docker compose, had to manually restart the kong container to make it work.
It looks kong starts before the kong-migration completely finishing up even you have this
```
    depends_on:
      kong_migration:
        condition: service_started
```
A temporary solution is to add `restart: on-failure` for kong.

**Comment by Thavaprakash** [comment]
Should i add below build in Dockerfile of kong? But it is not working.

```
kong:                                                                        
  build: kong/                                                               
  restart: on-failure  
```

**Comment by hutchic** [comment]
The kong migration commands are documented here [kong-migrations](https://docs.konghq.com/1.0.x/cli/#kong-migrations)

If `migration bootstrap` gets interrupted / times out etc run `migrations up` to complete any unfinished migrations
