### ISSUE TITLE
[alpine] Unable to set Timezone

### ISSUE THREAD

**Issue by bluemalkin** [Kong/docker-kong#124]
In Docker it is standard practice to pass an environment variable TZ=timezone to set the desired timezone in the container.

This does not work with the alpine Docker image because it's missing the tzdata package.

Can we please have this added to the Dockerfile ?

Thanks !

**Comment by bluemalkin** [comment]
PR raised - please approve ! 😃

**Comment by salazar** [comment]
Closing this - #125 has been merged. Thanks @bluemalkin!

**Comment by bluemalkin** [comment]
Thanks @salazar ! When can we expect this to be released please ?

**Comment by salazar** [comment]
@bluemalkin A new Kong version was released today. The Docker image is already up - check Docker store!
