### ISSUE TITLE
Kong doesn't start

### ISSUE THREAD

**Issue by moby04** [Kong/docker-kong#142]
I cloned the repository and tried to run `docker-compose up` without any changes. As a result kong_1 container doesn't start and the stack trace contains:

```
kong_1            | 2018/02/22 12:35:13 [warn] postgres database 'kong' is missing migration: (hmac-auth) 2015-09-16-132400_init_hmacauth
kong_1            | Error: /usr/local/share/lua/5.1/kong/cmd/start.lua:28: [postgres error] the current database schema does not match this version of Kong. Please run `kong migrations up` to update/initialize the database schema. Be aware that Kong migrations should only run from a single node, and that nodes running migrations concurrently will conflict with each other and might corrupt your database schema!
kong_1            | 
kong_1            |   Run with --v (verbose) or --vv (debug) for more details
kong_1            | prefix directory /usr/local/kong not found, trying to create it
compose_kong_1 exited with code 1
```

**Comment by gurdotan** [comment]
Same here...

**Comment by jeremyjpj0916** [comment]
I have seen similar problems and had to run migrations multiple times to try and fix this. One time it complained about the oauth2 table, once jwt, and then it works. Then I run it again and complains again about oauth2 table and cycle continues. very weird behavior from the migration functionality running against C*.

**Comment by Kahfimaulana** [comment]
I have same problem while running `kong` on `docker`. Solved problem with following guides right here [Docker Installation](https://getkong.org/install/docker). 
Try to remove container related to `kong` & `kong-database` then run:  

`docker run -d --name kong-database \
              -p 5432:5432 \
              -e "POSTGRES_USER=kong" \
              -e "POSTGRES_DB=kong" \
              postgres:9.4` . 

`docker run --rm \
    --link kong-database:kong-database \
    -e "KONG_DATABASE=postgres" \
    -e "KONG_PG_HOST=kong-database" \
    -e "KONG_CASSANDRA_CONTACT_POINTS=kong-database" \
    kong:latest kong migrations up` . 

`docker run -d --name kong \
    --link kong-database:kong-database \
    -e "KONG_DATABASE=postgres" \
    -e "KONG_PG_HOST=kong-database" \
    -e "KONG_CASSANDRA_CONTACT_POINTS=kong-database" \
    -e "KONG_PROXY_ACCESS_LOG=/dev/stdout" \
    -e "KONG_ADMIN_ACCESS_LOG=/dev/stdout" \
    -e "KONG_PROXY_ERROR_LOG=/dev/stderr" \
    -e "KONG_ADMIN_ERROR_LOG=/dev/stderr" \
    -e "KONG_ADMIN_LISTEN=0.0.0.0:8001" \
    -e "KONG_ADMIN_LISTEN_SSL=0.0.0.0:8444" \
    -p 8000:8000 \
    -p 8443:8443 \
    -p 8001:8001 \
    -p 8444:8444 \
    kong:latest`  

Added latest to every `kong` commands. 
Hope this help!

**Comment by tamvcspk** [comment]
Same here...It still can't be solved?

**Comment by BrokeRU** [comment]
The same trouble for me.

**Comment by thetrav** [comment]
Looks a bit like a race condition to me looks like kong's depends_on is going to wait for the migrations to start, not to complete, so if the migrations take longer than the kong startup then you'll get this error.

**Comment by vikaschauhan1** [comment]
Starting compose_kong-database_1 ... 
Starting compose_consul_1 ... 
Starting compose_kong-database_1
Starting compose_consul_1 ... done
Starting compose_nginx-lb_1 ... 
Starting compose_nginx-lb_1 ... done
Starting compose_kong-migration_1 ... 
Starting compose_kong-migration_1 ... done
Starting compose_kong-proxy_1 ... 
Starting compose_kong-proxy_1 ... done
Starting compose_konga_1 ... 
Starting compose_konga_1 ... done
Attaching to compose_kong-database_1, compose_consul_1, compose_nginx-lb_1, compose_kong-migration_1, compose_kong-proxy_1, compose_konga_1
kong-database_1   | LOG:  database system was shut down at 2018-07-28 11:44:26 UTC
consul_1          | ==> WARNING: Bootstrap mode enabled! Do not enable unless necessary
kong-database_1   | LOG:  MultiXact member wraparound protections are now enabled
consul_1          | ==> WARNING: It is highly recommended to set GOMAXPROCS higher than 1
kong-database_1   | LOG:  autovacuum launcher started
kong-database_1   | LOG:  database system is ready to accept connections
nginx-lb_1        | time="2018-07-28T11:45:16Z" level=debug msg="preStart.RunAndWait start" 
nginx-lb_1        | time="2018-07-28T11:45:16Z" level=debug msg=preStart.Cmd.Run 
consul_1          | ==> Starting raft data migration...
consul_1          | ==> Starting Consul agent...
nginx-lb_1        | time="2018-07-28T11:45:16Z" level=info msg="2018/07/28 11:45:16 [ERR] (vie



same trouble ----

**Comment by hutchic** [comment]
we have a test that validates our docker-compose now so I'm going to close this at this time 👍
