### ISSUE TITLE
The Kong docker image `kong:0.12.2` failed

### ISSUE THREAD

**Issue by Cospotato** [Kong/docker-kong#144]
The Kong docker image failed
The stdout print `/docker-entrypoint.sh: line 12: kong: command not found` when starting the container

Version: 0.12.2

Possible reason: The kong install was failed on image building stage. The rpm url in Dockerfile is `https://bintray.com/kong/kong-community-edition-rpm/download_file?file_path=dists%2Fkong-community-edition-0.12.2.el7.noarch.rpm`, returned 404. The url is actually `https://bintray.com/kong/kong-community-edition-rpm/download_file?file_path=centos%2F7%2Fkong-community-edition-0.12.2.el7.noarch.rpm`. The query parameter `file_path` is different.

**Comment by thibaultcha** [comment]
Hi, yes, we are aware and submitted a fix that is pending for review on the docker hub already. Thanks for reporting and sorry for the trouble!

**Comment by thibaultcha** [comment]
Btw, this should only affect the centos image. The alpine one should be fine.

**Comment by Cospotato** [comment]
Appreciate your work!

**Comment by CyExy** [comment]
@thibaultcha would it be possible to have the `latest` tag on `alpine`?

**Comment by thibaultcha** [comment]
@CyExy This will be our policy starting with 0.13

**Comment by thibaultcha** [comment]
This has been resolved now

**Comment by jaygorrell** [comment]
@thibaultcha I don't think it is resolved... am I missing something?

```
docker run -ti --rm kong:0.11.2 bash

Unable to find image 'kong:0.11.2' locally
0.11.2: Pulling from library/kong
5e35d10a3eba: Pull complete
eaea1d1a065c: Pull complete
8fa0dbcc3a61: Pull complete
Digest: sha256:0fc4dfaff0ae6618fdf3574b369cc803d0e7768792aaceee5e819d7995f65e79
Status: Downloaded newer image for kong:0.11.2

[root@d8cc7973db18 /]# cat /usr/local/
bin/     etc/     games/   include/ lib/     lib64/   libexec/ sbin/    share/   src/
```

There is no `kong` in `/usr/local/` still.

**Comment by optii** [comment]
I still have this issue also

```
docker run -ti --rm kong:0.11.2 bash
Unable to find image 'kong:0.11.2' locally
0.11.2: Pulling from library/kong
5e35d10a3eba: Already exists 
eaea1d1a065c: Pull complete 
8fa0dbcc3a61: Pull complete 
Digest: sha256:0fc4dfaff0ae6618fdf3574b369cc803d0e7768792aaceee5e819d7995f65e79
Status: Downloaded newer image for kong:0.11.2

[root@733f673e7ed8 /]# ls /usr/local/
bin  etc  games  include  lib  lib64  libexec  sbin  share  src

[root@733f673e7ed8 /]# kong
bash: kong: command not found

```

kong isn't there...

**Comment by CyExy** [comment]
@optii @jaygorrell Alpine version should work `docker run -ti --rm kong:0.12.2-alpine bash`

**Comment by jaygorrell** [comment]
It does, but this issue is specifically for the `kong:0.12.2` tag.

**Comment by optii** [comment]
Yes with alpine it does work, but that is not to the point, how did the 0.12.2 end up getting pushed to docker hub without `kong` in it... we've been using this version for a while without any problems.

Surely if a change was made to the docker the least that could have been checked is that `kong` actually exists on the image. I mean for stuff running in production it could end up being quite messy.

**Comment by coopr** [comment]
Hi All - I'm the Principal Product Manager here at Kong Inc. and I wanted to jump in this thread to say **I'm sorry**. This situation must have been annoying to all of you, and I want you to know that you can expect better of us. Thanks for your forgiveness, and thanks for being part of the Kong Community!
