### ISSUE TITLE
Compose: Kong Dockerfile fails

### ISSUE THREAD

**Issue by iwittkau** [Kong/docker-kong#151]
In `compose/kong/Dockerfile` the `curl` command fails due to the absence of a curl binary in the `kong` image: [Dockerfile:6](https://github.com/Kong/docker-kong/blob/914bba64bc7e1580b0e7e64e082459ca0c4e7eb7/compose/kong/Dockerfile#L6).

To try out the docker composition I added 

```Dockerfile
RUN apk add --no-cache curl
```

to the dockerfile on my machine, which resolves the issue temporally.

**Comment by etsrepo** [comment]
https://github.com/Kong/docker-kong/pull/152

**Comment by hutchic** [comment]
I believe this is resolved
