### ISSUE TITLE
standard_init_linux.go:195: exec user process caused "no such file or directory"

### ISSUE THREAD

**Issue by xiaodx12** [Kong/docker-kong#157]
when tried to
cd docker-kong/centos
docker build -f Dockerfile -t kong:dev .
docker run -it -p 8000:8000 -p 8443:8443 -p 8001:8001 kong:dev
return error:
standard_init_linux.go:195: exec user process caused "no such file or directory"

**Comment by rahimimo** [comment]
Did you find a workaround for it ?

**Comment by donalddewulf** [comment]
I'm not sure if this was the actual problem for me, but I had a similar error.
Seems to have been line endings that were not correct in docker-entrypoint.sh

Make sure it has linux line endings (\n)
