### ISSUE TITLE
fatal errors showing when executing docker-compose up

### ISSUE THREAD

**Issue by adeaj** [Kong/docker-kong#174]
Experiencing issues when trying to execute this docker image :

kong-migration_1  | statsd migrated up to: 2017-06-09-160000_statsd_schema_changes
kong_1            | 2018/09/12 13:51:03 [warn] postgres database 'kong' is missing migration: (basic-auth) 2017-01-25-180400_unique_username
kong_1            | **Error: /usr/local/share/lua/5.1/kong/cmd/start.lua:37: [postgres error] the current database schema does not match this version of Kong. Please run `kong migrations up` to update/initialize the database schema. Be aware that Kong migrations should only run from a single node, and that nodes running migrations concurrently will conflict with each other and might corrupt your database schema!**
kong_1            |
kong_1            |   Run with --v (verbose) or --vv (debug) for more details
kong-migration_1  | migrating jwt for database kong

kong-database_1   | FATAL:  role "postgres" does not exist

**Comment by adeaj** [comment]
steps to reproduce:

1.- clone repo
2. - execute docker-compose up in compose folder

MacOs Sierra 10.12.6
Docker version - Version 18.03.1-ce-mac65

**Comment by PFadel** [comment]
Same issue here with Ubuntu 18.04.1 and docker version 18.06.1-ce.

**Comment by iperdomo** [comment]
I was able to run the system with this change:

```diff
diff --git a/compose/docker-compose.yml b/compose/docker-compose.yml
index 0ce8139..ccd388c 100644
--- a/compose/docker-compose.yml
+++ b/compose/docker-compose.yml
@@ -49,7 +49,7 @@ services:
       - POSTGRES_USER=kong
       - POSTGRES_DB=kong
     healthcheck:
-      test: ["CMD", "pg_isready", "-U", "postgres"]
+      test: ["CMD", "pg_isready", "-U", "kong"]
       interval: 10s
       timeout: 5s
       retries: 5
```
