### ISSUE TITLE
Docker: replacement for KONG_CUSTOM_PLUGINS variable environment

### ISSUE THREAD

**Issue by cmidt-veasna** [Kong/docker-kong#176]
The new release of KONG 0.14.1 has deprecated the **custom_plugins** configurations and recommend to use **plugins** instead as mention [here](https://github.com/Kong/kong/blob/master/UPGRADE.md#2-deprecation-notices). However it seem there is no document mention what is the replacement for **KONG_CUSTOM_PLUGINS** variable environment. Below is the output from KONG docker image 

`2018/09/24 14:33:14 [warn] the 'custom_plugins' configuration property is deprecated, use 'plugins' instead`

**Comment by coopr** [comment]
Does https://docs.konghq.com/0.14.x/configuration/#plugins clarify it for you?

If not, please clarify the issue you are encountering. 

Also, if this is not a bug, please move this discussion to Kong Nation https://discuss.konghq.com/ - we reserve Github Issues for bug reports.

**Comment by gszr** [comment]
Hi, @cmidt-veasna. As with any Kong configuration directive, the environment variable counterpart follows the format `KONG_` + the directive name all in uppercase; in this particular case, `KONG_PLUGINS` is what you are looking for. Have a look at [this](https://docs.konghq.com/0.14.x/configuration/#environment-variables). As mentioned by Cooper, we reserve GitHub issues for bug reports; if you have any more questions, please visit [Kong Nation](https://discuss.konghq.com/).

**Comment by cmidt-veasna** [comment]
@gszr @coopr Thanks for clarification.
