### ISSUE TITLE
FATAL:  role "postgres" does not exist  docker-kong

### ISSUE THREAD

**Issue by ANTISEC12** [Kong/docker-kong#179]
Hello myfriends, 
I run docker-kong on Docker (Docker version 17.12.1-ce, build 7390fc6 / Debian)
When i run `docker-compose up ` 

> ../pathtoDOCKER-COMPOSE.YML/ 

after download dependencies (DockerImages) ... 
[image_log](https://imggmi.com/full/2018/9/30/cdfc41e3bd7e55773d4272f412095f55-full.png.html)

Now, how to solve my problem?

**Comment by pugwoo** [comment]
I also encountered this problem.  Docker version: 18.06.1-ce on Debian 8

**Comment by ANTISEC12** [comment]
> I also encountered this problem. Docker version: 18.06.1-ce on Debian 8

and, how solved that?

**Comment by pugwoo** [comment]
> > I also encountered this problem. Docker version: 18.06.1-ce on Debian 8
> 
> and, how solved that?

I don't know.

**Comment by pugwoo** [comment]
> > I also encountered this problem. Docker version: 18.06.1-ce on Debian 8
> 
> and, how solved that?

I don't know how to solve it. 

I did as this post https://docs.konghq.com/install/docker/ and installed success on docker. not the compose way.

**Comment by AhmadRafiee** [comment]
`version: '2.1'

services:
  kong-database:
    image: postgres:9.6
    environment:
      - POSTGRES_USER=kong
      - POSTGRES_DB=kong
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  kong-migration:
    image: kong
    depends_on:
      kong-database:
        condition: service_healthy
    environment:
      - KONG_DATABASE=postgres
      - KONG_PG_HOST=kong-database
    command: kong migrations up

  kong:
    image: kong:latest
    container_name: kong
    depends_on:
      kong-database:
        condition: service_healthy
      kong-migration:
        condition: service_started
    environment:
      - KONG_DATABASE=postgres
      - KONG_PG_HOST=kong-database
      - KONG_PG_DATABASE=kong
      - KONG_ADMIN_LISTEN=0.0.0.0:8001, 0.0.0.0:8444 ssl
    ports:
      - 8000:8000
      - 8001:8001
      - 8443:8443
      - 8444:8444
    healthcheck:
      test: ["CMD-SHELL", "curl -I -s -L http://127.0.0.1:8000 || exit 1"]
      interval: 5s
      retries: 10`
**How to run:**
`docker-compose up -d ; sleep 10 ; docker start kong`

**Comment by ANTISEC12** [comment]
> `version: '2.1'
> 
> services:
> kong-database:
> image: postgres:9.6
> environment:
> - POSTGRES_USER=kong
> - POSTGRES_DB=kong
> healthcheck:
> test: ["CMD", "pg_isready", "-U", "postgres"]
> interval: 10s
> timeout: 5s
> retries: 5
> 
> kong-migration:
> image: kong
> depends_on:
> kong-database:
> condition: service_healthy
> environment:
> - KONG_DATABASE=postgres
> - KONG_PG_HOST=kong-database
> command: kong migrations up
> 
> kong:
> image: kong:latest
> container_name: kong
> depends_on:
> kong-database:
> condition: service_healthy
> kong-migration:
> condition: service_started
> environment:
> - KONG_DATABASE=postgres
> - KONG_PG_HOST=kong-database
> - KONG_PG_DATABASE=kong
> - KONG_ADMIN_LISTEN=0.0.0.0:8001, 0.0.0.0:8444 ssl
> ports:
> - 8000:8000
> - 8001:8001
> - 8443:8443
> - 8444:8444
> healthcheck:
> test: ["CMD-SHELL", "curl -I -s -L http://127.0.0.1:8000 || exit 1"]
> interval: 5s
> retries: 10`
> 
> **How to run:**
> 
> `docker-compose up -d ; sleep 10 ; docker start kong`

Ok, I will run `docker-compose up ; sleep 10 ; docker start kong` and now get the following error; 
[FATAL:  role "postgres" does not exist
compose_kong_1 exited with code 132](https://pastebin.com/p9C47Ns8)

**Comment by elliottfrantz** [comment]
You are missing the -d switch, does that resolve the issue? The last command should also be 'docker-compose'.

```
docker-compose up -d
sleep 10
docker-compose start kong
```

**Comment by hutchic** [comment]
looks like this is resolved now 👍
