### ISSUE TITLE
FATAL:  role "postgres" does not exist

### ISSUE THREAD

**Issue by travega** [Kong/docker-kong#180]
I try `docker-compose up` and I get the fatal error: `FATAL:  role "postgres" does not exist`

I'm using `Docker version 18.06.1-ce, build e68fc7a` on a Mac.

In case it's pertinent I installed Kong initially using the instruction [here](https://docs.konghq.com/install/docker/). Then deleted the images after getting the above error. I did also run a `docker-compose build` before `docker-compose up`.

Any ideas?

**Comment by elliottfrantz** [comment]
Try
```
docker-compose up -d ; sleep 10 ; docker start kong
```

**Comment by Tieske** [comment]
fixed by #189
