### ISSUE TITLE
syslog plugin disabled by default

### ISSUE THREAD

**Issue by wen911119** [Kong/docker-kong#183]
I used Syslog plugin to record logs, but it did not work as expected. I can not find log file in the path '/var/log/'.
![20181019180723](https://user-images.githubusercontent.com/13494648/47212523-045fa900-d3cb-11e8-819e-7b034205a3b9.png)
I try to start it manually
`syslogd `
every thing is ok now

![20181019182351](https://user-images.githubusercontent.com/13494648/47213178-db401800-d3cc-11e8-8605-67c0e7802506.png)
![20181019182421](https://user-images.githubusercontent.com/13494648/47213185-df6c3580-d3cc-11e8-9aa8-378c7ee63c84.png)

**Comment by wen911119** [comment]
#https://github.com/Kong/kong/issues/3178

**Comment by wen911119** [comment]
version: 
kong:latest
kong:0.13-alpine

**Comment by satishmane** [comment]
Hi,
I am facing same issue. syslogd does not start automatically as part of kong docker image. it works manually. Did you manage to get it working?

**Comment by hutchic** [comment]
syslogd is not bundled with or started automatically as part of Kong.

You will need to install / configure / run syslog separately after which the Kong syslog plugin is able to send logs to it. I did a quick test of Kong 2.0.2 on Xenial and everything works as expected.
