### ISSUE TITLE
Is Kong 1.0.0 released in docker hub?

### ISSUE THREAD

**Issue by JoyZhang66** [Kong/docker-kong#204]
I see Kong 1.0.0 release info but can not find this version image in docker hub. I wonder if Kong 1.0.0 is released in docker hub?

![releaseinfo](https://user-images.githubusercontent.com/27359184/50263669-ead1f080-0451-11e9-8422-beac4de12b7e.png)
![released](https://user-images.githubusercontent.com/27359184/50263686-00dfb100-0452-11e9-9f00-63cfac1574ae.png)

**Comment by thibaultcha** [comment]
It is in progress: https://github.com/docker-library/official-images/pull/5209

**Comment by JoyZhang66** [comment]
Thank you for your reply.

**Comment by pgold30** [comment]
Hi guys, i dont see the image 1.0.0-alpine, im looking in  https://hub.docker.com/_/kong/, is that the right page ? do you know when the image will be ready?
