### ISSUE TITLE
Kong migrations command in compose file is incorrect

### ISSUE THREAD

**Issue by mohitmutha** [Kong/docker-kong#207]
**kong-migrations_1  | No such command for migrations: bootstrap**
kong-migrations_1  |
kong-migrations_1  | Usage: kong migrations COMMAND [OPTIONS]
kong-migrations_1  |
kong-migrations_1  | Manage Kong's database migrations.
kong-migrations_1  |
kong-migrations_1  | The available commands are:
kong-migrations_1  |  list   List migrations currently executed.
kong-migrations_1  |  up     Execute all missing migrations up to the latest available.
kong-migrations_1  |  reset  Reset the configured database (irreversible).
kong-migrations_1  |
kong-migrations_1  | Options:
kong-migrations_1  |  -c,--conf        (optional string) configuration file
kong-migrations_1  |  -y,--yes         assume "yes" to prompts and run non-interactively
kong-migrations_1  |  --v              verbose
kong-migrations_1  |  --vv             debug
kong_kong-migrations_1 exited with code 1

Getting a error. This needs to be changed to kong migrations up

**Comment by Tieske** [comment]
this is for the new 0.15.0 and 1.0 versions, which haven't yet landed in docker hub. The migrations command was changed from `kong migrations up` to `kong migrations bootstrap`.

So a temporary in-between state. Will auto-resolve when the new images land.
