### ISSUE TITLE
User will be changed from kong to nobody after 'kong reload'

### ISSUE THREAD

**Issue by JoyZhang66** [Kong/docker-kong#219]
I run kong in docker as user 'kong'. But after I run 'kong reload' command, user change to nobody. As a result, I can't write data to some temp files.  How can I solve this problem?

Command:
docker exec -it kong kong reload

Before:
![kong_user](https://user-images.githubusercontent.com/27359184/51370231-61d1d600-1b31-11e9-805f-e55e7103ae77.png)

After:
![nobody](https://user-images.githubusercontent.com/27359184/51370296-947bce80-1b31-11e9-97c8-24bc9a19bea4.png)

**Comment by hutchic** [comment]
You may need to `chmod` or `kong prepare` the directory in question similar to this https://github.com/Kong/docker-kong/blob/master/alpine/docker-entrypoint.sh#L15-L16
