### ISSUE TITLE
Cannot scale kong services

### ISSUE THREAD

**Issue by kavaka123** [Kong/docker-kong#221]
I see the below error when scaling kong service to 3. Any suggestions on how to fix this?

WARNING: The scale command is deprecated. Use the up command with the --scale flag instead.
WARNING: The "kong" service specifies a port on the host. If multiple containers for this service are created on a single host, the port will clash.
Starting compose_kong_1 ... done
Creating compose_kong_2 ...
Creating compose_kong_3 ...
Creating compose_kong_2 ... error
Creating compose_kong_3 ... error

ERROR: for compose_kong_3  Cannot start service kong: driver failed programming external connectivity on endpoint compose_kong_3 (23208155793a5b42af1807458bdb65977835e668750216c43932545d03fd28d5): Bind for 0.0.0.0:8444 failed: port is already allocated

ERROR: for compose_kong_2  Cannot start service kong: driver failed programming external connectivity on endpoint compose_kong_2 (9e9b470cd349fef673022998f3c4ebbfdc7af6f1671f8a958aeb539460b37302): Bind for 0.0.0.0:8444 failed: port is already allocated
ERROR: Cannot start service kong: driver failed programming external connectivity on endpoint compose_kong_3 (23208155793a5b42af1807458bdb65977835e668750216c43932545d03fd28d5): Bind for 0.0.0.0:8444 failed: port is already allocated

**Comment by Tieske** [comment]
That is to be expected, see https://stackoverflow.com/questions/36426823/can-not-scale-service-to-multiple-container-when-binding-host-port-in-docker-com for example

**Comment by hutchic** [comment]
@kavaka123 can you give this PR a quick test for me? https://github.com/Kong/docker-kong/pull/229

**Comment by gszr** [comment]
As Tieske mentioned, this is expected, as there is a port being bound on the host. Closing this as stale. Please reopen if needed.
