### ISSUE TITLE
plugin not enabled, add it to plugins configuration

### ISSUE THREAD

**Issue by benpetsch** [Kong/docker-kong#227]
How to use 3rd party plugins with docker kong?

I'm just getting started, following the guide

1. https://docs.konghq.com/install/docker/
2. https://docs.konghq.com/1.0.x/getting-started/quickstart/
3. https://docs.konghq.com/hub/moesif/kong-plugin-moesif/
4. Request send
```
curl -X POST http://localhost:8001/services/example-service/plugins \
    --data "name=kong-plugin-moesif"  \
    --data "config.application_id=MY_MOESIF_APPLICATION_ID"
```
5. Running into error message:
```
{
"message":"schema violation (name: plugin 'kong-plugin-moesif' not enabled; add it to the 
'plugins' configuration property)",
"name":"schema violation",
"fields":{
"name":"plugin 'kong-plugin-moesif' not enabled; add it to the 'plugins' 
configuration property"
},
"code":2
}
```

**Comment by Tieske** [comment]
See #205

**Comment by emanuellandell** [comment]
same here!

**Comment by caseyra** [comment]
You have to make sure you load the plugin: https://docs.konghq.com/1.1.x/plugin-development/distribution/#load-the-plugin

You can also do this via the KONG_PLUGINS enviroment variable.

**Comment by jainrocks** [comment]
I have uncommented the line :

> plugins = bundled,simple-plugin

and added my plugin named 

> simple-plugin

But, still getting 
`{
    "message": "schema violation (name: plugin 'simple-plugin' not enabled; add it to the 'plugins' configuration property)",
    "name": "schema violation",
    "fields": {
        "name": "plugin 'simple-plugin' not enabled; add it to the 'plugins' configuration property"
    },
    "code": 2
}`

**Comment by hbagdi** [comment]
@jainrocks You need to change it in `kong.conf` and not `kong.conf.default`.

**Comment by jainrocks** [comment]
@hbagdi,
Yes I replaced, kong.conf.default with kong.conf, with the only line in the file as below:
`plugins = bundled,simple-plugin` 

But, I am getting:
`2020/01/30 07:34:05 [error] 1#0: init_by_lua error: /usr/local/share/lua/5.1/kong/init.lua:425: error loading plugin schemas: on plugin 'simple-plugin': simple-plugin plugin is enabled but not installed;
module 'kong.plugins.simple-plugin.handler' not found:No LuaRocks module found for kong.plugins.simple-plugin.handler
	no field package.preload['kong.plugins.simple-plugin.handler']
	no file './kong/plugins/simple-plugin/handler.lua'
	no file './kong/plugins/simple-plugin/handler/init.lua'
	no file '/usr/local/openresty/site/lualib/kong/plugins/simple-plugin/handler.ljbc'
	no file '/usr/local/openresty/site/lualib/kong/plugins/simple-plugin/handler/init.ljbc'
	no file '/usr/local/openresty/lualib/kong/plugins/simple-plugin/handler.ljbc'
	no file '/usr/local/openresty/lualib/kong/plugins/simple-plugin/handler/init.ljbc'
	no file '/usr/local/openresty/site/lualib/kong/plugins/simple-plugin/handler.lua'
	no file '/usr/local/openresty/site/lualib/kong/plugins/simple-plugin/handler/init.lua'
	no file '/usr/local/openresty/lualib/kong/plugins/simple-plugin/handler.lua'
	no file '/usr/local/openresty/lualib/kong/plugins/simple-plugin/handler/init.lua'
	no file '/usr/local/openresty/luajit/share/luajit-2.1.0-beta3/kong/plugins/simple-plugin/handler.lua'
	no file '/usr/local/share/lua/5.1/kong/plugins/simple-plugin/handler.lua'
	no file '/usr/local/share/lua/5.1/kong/plugins/simple-plugin/handler/init.lua'
	no file '/usr/local/openresty/luajit/share/lua/5.1/kong/plugins/simple-plugin/handler.lua'
	no file '/usr/local/openresty/luajit/share/lua/5.1/kong/plugins/simple-plugin/handler/init.lua'
	no file '/home/kong/.luarocks/share/lua/5.1/kong/plugins/simple-plugin/handler.lua'
	no file '/home/kong/.luarocks/share/lua/5.1/kong/plugins/simple-plugin/handler/init.lua'
	no file '/usr/local/openresty/site/lualib/kong/plugins/simple-plugin/handler.so'
	no file '/usr/local/openresty/lualib/kong/plugins/simple-plugin/handler.so'
	no file './kong/plugins/simple-plugin/handler.so'
	no file '/usr/local/lib/lua/5.1/kong/plugins/simple-plugin/handler.so'
	no file '/usr/local/openresty/luajit/lib/lua/5.1/kong/plugins/simple-plugin/handler.so'
	no file '/usr/local/lib/lua/5.1/loadall.so'
	no file '/home/kong/.luarocks/lib/lua/5.1/kong/plugins/simple-plugin/handler.so'
	no file '/usr/local/openresty/site/lualib/kong.so'
	no file '/usr/local/openresty/lualib/kong.so'
	no file './kong.so'
	no file '/usr/local/lib/lua/5.1/kong.so'
	no file '/usr/local/openresty/luajit/lib/lua/5.1/kong.so'
	no file '/usr/local/lib/lua/5.1/loadall.so'
	no file '/home/kong/.luarocks/lib/lua/5.1/kong.so'
stack traceback:
	[C]: at 0x7fcca44fb0d0
	[C]: in function 'xpcall'
	/usr/local/share/lua/5.1/kong/tools/utils.lua:611: in function 'load_module_if_exists'
	/usr/local/share/lua/5.1/kong/db/dao/plugins.lua:149: in function 'load_plugin_handler'
	/usr/local/share/lua/5.1/kong/db/dao/plugins.lua:227: in function 'load_plugin'
	/usr/local/share/lua/5.1/kong/db/dao/plugins.lua:275: in function 'load_plugin_schemas'
	/usr/local/share/lua/5.1/kong/init.lua:425: in function 'init'
	init_by_lua:3: in main chunk
stack traceback:
	[C]: in function 'assert'
	/usr/local/share/lua/5.1/kong/init.lua:425: in function 'init'
	init_by_lua:3: in main chunk
`

**Comment by jainrocks** [comment]
Got it, I added the simple-plugin folder in:
`/usr/local/share/lua/5.1/kong/plugins`
Now, this plugin is working fine.

**Comment by basarkoc1843** [comment]
Hi,i am getting the same error.there is no such file in my locale lua/5.1/kong/plugins. Can you explain in detail how you did it?
