### ISSUE TITLE
Docker-kong does not run on openshift

### ISSUE THREAD

**Issue by zoobab** [Kong/docker-kong#231]
Hi,

Just hit this issue on an openshift 3.11 cluster:

```
chmod: /proc/self/fd/1: Permission denied
```

I made a change to do not run as a unix kong user, but as root, and it works, see:

https://github.com/zoobab/docker-kong/commit/980efca807705df117fac61f4b83987fe5174ff4

I am trying to see if running with the anyuid permission would help to solve the issue in another way...

**Comment by Tieske** [comment]
@svenwal any ideas?

**Comment by svenwal** [comment]
If you want to run a arbitrary user (anyuid) you need (as of 1.1.0rc1) to create a slightly different Dockerfile which does not use the root user at all.

I have it available at https://github.com/svenwal/docker-kong/tree/master/alpine (Alpine "only") so if you use this one to create your own Docker image and have it in your Docker registry in OpenShift you can start Kong without any modifications to OpenShift settings about root user or similar.

**Comment by zoobab** [comment]
I forked your repo, and made a build:

zoobab/kong:1.1.0rc1-openshift

You can also use latest, it is the same.

zoobab/kong

**Comment by yangbo1987** [comment]
how you solve it  
i use like  https://docs.konghq.com/install/docker/?_ga=2.143449205.1710915732.1554184870-1817960271.1554184870

when i run 
 docker run -d --name kong -u root \
     --network=kong-net \
     -e "KONG_DATABASE=postgres" \
     -e "KONG_PG_HOST=kong-database" \
     -e "KONG_CASSANDRA_CONTACT_POINTS=kong-database" \
     -e "KONG_PROXY_ACCESS_LOG=/dev/stdout" \
     -e "KONG_ADMIN_ACCESS_LOG=/dev/stdout" \
     -e "KONG_PROXY_ERROR_LOG=/dev/stderr" \
     -e "KONG_ADMIN_ERROR_LOG=/dev/stderr" \
     -e "KONG_ADMIN_LISTEN=0.0.0.0:8001, 0.0.0.0:8444 ssl" \
     -p 8000:8000 \
     -p 8443:8443 \
     -p 8001:8001 \
     -p 8444:8444 \
     kong:latest

i  use "docker logs 63d340420945 " i got like 

chmod: /proc/self/fd/1: Permission denied

ps :63d340420945  is kong' containerId

**Comment by hutchic** [comment]
resolved in https://github.com/Kong/docker-kong/pull/243 (which isn't in the official images yet)
