### ISSUE TITLE
Docker install instructions (non-compose) missing KONG_PG_HOST

### ISSUE THREAD

**Issue by lukego** [Kong/docker-kong#232]
The [setup instructions on Dockerhub](https://hub.docker.com/_/kong/) seem to need one more configuration parameter when starting the kong container in order to successfully connect with the postgresql database container:

```
-e KONG_PG_HOST=kong-database
```

otherwise it will default to `kong` as the database hostname and fail to connect.

(Cassandra mode seems to already have an equivalent setting.)

**Comment by hutchic** [comment]
Thanks for pointing that out. This has since been resolved https://github.com/docker-library/docs/pull/1453
