### ISSUE TITLE
Change port to listen for incoming HTTP/HTTPS traffic using Docker image

### ISSUE THREAD

**Issue by ldm810** [Kong/docker-kong#240]
I am running Kong using the docker image. If I want to change the port for incoming HTTP/HTTPS traffic from clients to 9000/9443 respectively. 

Do I need to modify the underlying NGINX configurations and rebuild the Docker image to do so? If so, can you provide instructions on how to do so?

Otherwise, can you advise on how to do this?

I tried running kong with the command below but I get the following error:
```
curl -i -X GET   --url http://localhost:9000/   --header 'Host: example.com'
curl: (7) Failed to connect to localhost port 9000: Connection refused
```

```
docker run -d --name kong \
     --network=kong-net \
     -e "KONG_DATABASE=postgres" \
     -e "KONG_PG_HOST=kong-database" \
     -e "KONG_CASSANDRA_CONTACT_POINTS=kong-database" \
     -e "KONG_PROXY_ACCESS_LOG=/dev/stdout" \
     -e "KONG_ADMIN_ACCESS_LOG=/dev/stdout" \
     -e "KONG_PROXY_ERROR_LOG=/dev/stderr" \
     -e "KONG_ADMIN_ERROR_LOG=/dev/stderr" \
     -e "KONG_ADMIN_LISTEN=0.0.0.0:9001, 0.0.0.0:9444 ssl" \
     -p 8000:9000 \
     -p 8443:9443 \
     -p 9001:9001 \
     -p 9444:9444 \
     kong:latest
```

**Comment by apoorvkapil** [comment]
@ldm810 No need to change the nginx configuration and rebuild. Docker run command you are passing should be sufficient.
This seems you are trying to access container port (9000) that is exposed as 8000 from your local machine. try to hit same command on port 8000 this should work.
