### ISSUE TITLE
Why do we need to pass the destination service/route in the header of a request?

### ISSUE THREAD

**Issue by ldm810** [Kong/docker-kong#241]
In the documentation below, you can test that Kong is forwarding requests to the service, you need to include the host in the header. Is this how we would ask users to hit our api?
```
curl -i -X GET \
  --url http://localhost:8000/ \
  --header 'Host: example.com'
```

https://docs.konghq.com/1.0.x/getting-started/configuring-a-service/

**Comment by Tieske** [comment]
in a normal way of requested an http endpoint, you'd use either a browser or a client library to make a http request. You provide it with the endpoint you want to fetch.

For example add `https://example.com/some/path` in your browser. The browser (or client library) will then based on the url provided automatically add the header `Host: example.com`. So there is no specific "ask" to your users.
