### ISSUE TITLE
Installing Kong on ECS fargate with external DB using CloudFormation

### ISSUE THREAD

**Issue by apoorvkapil** [Kong/docker-kong#242]
Is their any pre-built cloudformation script to install Kong on **ECS fargate** with external Postgres RDS in AWS.
I have used **EC2 cloudformation template** but has doubt on **user/data commands** provided for EC2 Instances and what needs to be done in case of running docker image and how to pass data.

**Comment by hutchic** [comment]
None that I know of but if you come across one (or make one) we could add it to the deployment section of https://docs.konghq.com/hub/

**Comment by apoorvkapil** [comment]
@hutchic Thanks for updating, sure i am creating one and will share it soon.

let's keep this issue open.

**Comment by iniinikoski** [comment]
Hi, about this one, sorry for hijacking the ticket but... Is anyone running Kong successfully in Fargate? We are running still 1.0.3 - and Kong tends to be run out of disk space...

This was the only "Kong Fargate" I could Google...

**Comment by apoorvkapil** [comment]
@iniinikoski would like to know the task definition Configuration of your deployment ? Also if you are running it in Production  , there are Production System Requirements listed on Kong page. Please check if you are inline with that.
[](https://docs.konghq.com/enterprise/0.32-x/kong-implementation-checklist/)

**Comment by iniinikoski** [comment]
I'll report back soon - with a task definition JSON as well. The proxy cache was filling up, we did some... tweaks :) And so far everything looks good. Let's give it a few weeks of continuous running after conclusions :)

I only found some old documentation (of Kong Enterprise) on "Production System Requirements" - but not on the latest docs. The old docs mentioned "24 GB of disk", Fargate only has 10 gigs maximum.

Let's see... This is an interesting experiment.

**Comment by manuelnucci** [comment]
Is it viable in ECS + Fargate? The issue was never resolved.

**Comment by iniinikoski** [comment]
@manuelnucci ECS + Fargate itself works - but I haven't seen anyone to build CloudFormation around this + sharing the creation... We're not deploying Kong with Cloudformation - only the infrastructure around it is in CFN...

But, looking at our Task Definitions, I'd say there's nothing special around Kong+Fargate - it's just another ECS Fargate service...
