### ISSUE TITLE
UID 1337 conflict with Istio

### ISSUE THREAD

**Issue by ismailbaskin** [Kong/docker-kong#257]
According to[ Istio requirements](https://istio.io/docs/setup/kubernetes/prepare/requirements/) applications should not run as a user with the user ID (UID) value of 1337. 

I know it's pretty noob number but what do you think about changing uid to different than [1337](https://github.com/Kong/docker-kong/blob/master/alpine/Dockerfile#L7) ? 

Many thanks.

**Comment by hutchic** [comment]
We default to running with UID 1337 for the purpose of integrating with `istio/proxy_init` when Kong is deployed as a service mesh but we do allow one to run with a different UID so long as that UID isn't 0 (this was done to fix openshift)

```
KONG_USER=1000 docker-compose up -d
~/projects/docker-kong/compose$ docker-compose exec kong /bin/sh
/ $ ps aux
PID   USER     TIME   COMMAND
    1 1000       0:00 nginx: master process /usr/local/openresty/nginx/sbin/nginx -p /usr/local/kong -c nginx.conf
   30 1000       0:00 nginx: worker process
   31 1000       0:00 nginx: worker process
   32 1000       0:00 /bin/sh
   37 1000       0:00 ps aux
```

Any further customization I suspect you'll need to fork / build your own image. If you keep it backwards compatible (ie take the UID as a build_arg and default it to 1337) I think we'd merge it 👍
