### ISSUE TITLE
Kong 1.2.0 still throws errors in openshift

### ISSUE THREAD

**Issue by zoobab** [Kong/docker-kong#267]
Hi,

I built an image ```zoobab/kong:1.2.0```, but when I run it on openshift, I still get:

```
# oc logs kong
chmod: /proc/self/fd/1: Permission denied
chmod: /proc/self/fd/2: Permission denied
nginx: [emerg] open() "/dev/stderr" failed (13: Permission denied)
```

I am rolling back to my version with fixes on ```zoobab/kong:1.1.1-openshift``` till there is a real fix to run it on openshift.

Best

**Comment by hutchic** [comment]
I'm unable to reproduce any issues with OpenShift.

There's enough reports I suspect there might be something amiss but going to close this issue and keep all OpenShift discussion in one place https://github.com/Kong/kong/issues/4576#issuecomment-498632894
