### ISSUE TITLE
chmod: changing permissions of '/proc/self/fd/1': Permission denied on CentOS 7

### ISSUE THREAD

**Issue by afshinm** [Kong/docker-kong#274]
I'm using CentOS 7.x and I'm getting this error during container bootstrap:

 ```
kong_1             | chmod: changing permissions of '/proc/self/fd/1': Permission denied
kong_1             | chmod: changing permissions of '/proc/self/fd/2': Permission denied
kong_1             | nginx: [emerg] open() "/dev/stderr" failed (13: Permission denied)
```
I'm running the container as `root`.

**Comment by hutchic** [comment]
The changing permission warnings are typically fine and are warning we ignore. The real error is the `nginx: [emerg] open() "/dev/stderr"`

This is going to be related to https://github.com/moby/moby/issues/31243 and in that thread you can see that we've used one of the suggested workarounds. I'm noticing the workaround doesn't work in all cases and believe it's related to the host environment setup.

Can you send:
```
docker version
lsb_release -a
how you installed docker
command you ran the kong container with
```

**Comment by DUWENINK** [comment]
i have the same issue 
i use Hyper-v and install a linux(Cnetos7 x64) then i install a docker in it  
this is my docker version 
`[root@localhost ~]# docker version                                                                                                                                
Client:
 Version:         1.13.1
 API version:     1.26
 Package version: docker-1.13.1-96.gitb2f74b2.el7.centos.x86_64
 Go version:      go1.10.3
 Git commit:      b2f74b2/1.13.1
 Built:           Wed May  1 14:55:20 2019
 OS/Arch:         linux/amd64

Server:
 Version:         1.13.1
 API version:     1.26 (minimum version 1.12)
 Package version: docker-1.13.1-96.gitb2f74b2.el7.centos.x86_64
 Go version:      go1.10.3
 Git commit:      b2f74b2/1.13.1
 Built:           Wed May  1 14:55:20 2019
 OS/Arch:         linux/amd64
 Experimental:    false` 

this is my command
`docker run -d --name kong \
--link kong-database:kong-database \
-e "KONG_DATABASE=postgres" \
-e "KONG_PG_HOST=kong-database" \
-e "KONG_PG_PASSWORD=kong" \
-e "KONG_CASSANDRA_CONTACT_POINTS=kong-database" \
-e "KONG_PROXY_ACCESS_LOG=/dev/stdout" \
-e "KONG_ADMIN_ACCESS_LOG=/dev/stdout" \
-e "KONG_PROXY_ERROR_LOG=/dev/stderr" \
-e "KONG_ADMIN_ERROR_LOG=/dev/stderr" \
-e "KONG_ADMIN_LISTEN=0.0.0.0:8001, 0.0.0.0:8444 ssl" \
-p 8000:8000 \
-p 8443:8443 \
-p 8001:8001 \
-p 8444:8444 \
kong`

**Comment by DUWENINK** [comment]
the docment on the website is out of date,please update

**Comment by simsq** [comment]
> 我正在使用CentOS 7.x，我在容器引导期间遇到此错误：
> 
> ```
> kong_1             | chmod: changing permissions of '/proc/self/fd/1': Permission denied
> kong_1             | chmod: changing permissions of '/proc/self/fd/2': Permission denied
> kong_1             | nginx: [emerg] open() "/dev/stderr" failed (13: Permission denied)
> ```
> 
> 我正在运行容器`root`。

把Docker升级为最新版本就OK了。

**Comment by baokong** [comment]
@afshinm can you more information what platform you are running the image on? I notice we have some similar errors when running on Openshift.

**Comment by DUWENINK** [comment]
> @afshinm can you more information what platform you are running the image on? I notice we have some similar errors when running on Openshift.

just update your docker to lastest

**Comment by Chauncylcx** [comment]
disabled selinux

**Comment by JuniorCtba** [comment]
I just have thin in error in beginning of the logs.

chmod: changing permissions of '/proc/self/fd/1': Permission denied
--
  | chmod: changing permissions of '/proc/self/fd/2': Permission denied
  | 2019/10/04 10:11:42 [info] 1#0: [lua] mesh.lua:64: init(): initialising cluster ca...
  | 2019/10/04 10:11:42 [info] 1#0: [lua] mesh.lua:137: init(): cluster ca initialised
  | 2019/10/04 10:11:42 [notice] 1#0: using the "epoll" event method
  | 2019/10/04 10:11:42 [notice] 1#0: openresty/1.15.8.1
  | 2019/10/04 10:11:42 [notice] 1#0: built by gcc 4.8.5 20150623 (Red Hat 4.8.5-36) (GCC)
  | 2019/10/04 10:11:42 [notice] 1#0: OS: Linux 3.10.0-1062.el7.x86_64
  | 2019/10/04 10:11:42 [notice] 1#0: getrlimit(RLIMIT_NOFILE): 1048576:1048576
  | 2019/10/04 10:11:42 [notice] 1#0: start worker processes
  | 2019/10/04 10:11:42 [notice] 1#0: start worker process 31

But it is working.

**Comment by flbla** [comment]
Hello,
I'm getting the same issue when selinux is enabled with setenforce 1 (enforcing mode).

**Comment by hutchic** [comment]
As of `1.5.0` and `2.0.0` the Kong containers no longer require setcap and run as a less privileged Kong user
