### ISSUE TITLE
Is it necessary to have kong-migration in docker-compose file

### ISSUE THREAD

**Issue by rakehell1986** [Kong/docker-kong#275]
Hi everyone

is it necessary to have kong-migration node configured in docker-compose file? 

please take a look at my config as below. that doesn't work with below error.

sat_kong:
    build: ./kong
    container_name: kong
    **command: "kong migrations bootstrap"**
    environment:
      - KONG_DATABASE=postgres
      - KONG_PG_HOST=sat_db
      - KONG_CASSANDRA_CONTACT_POINTS=sat_db
      - KONG_PG_PASSWORD=12322321
      - KONG_PROXY_ACCESS_LOG=/dev/stdout
      - KONG_ADMIN_ACCESS_LOG=/dev/stdout
      - KONG_PROXY_ERROR_LOG=/dev/stderr
      - KONG_ADMIN_ERROR_LOG=/dev/stderr
      - KONG_ADMIN_LISTEN=0.0.0.0:8001,0.0.0.0:8444 ssl
    ports:
      - "8000:8000/tcp"
      - "8001:8001/tcp"
      - "8443:8443/tcp"
      - "8444:8444/tcp"
    depends_on:
      - sat_db
    restart: on-failure
    links:
      - sat_db

[root@smartagent-VODC sat-docker]# docker logs -f kong
Error: [PostgreSQL error] failed to retrieve server_version_num: connection refused

  Run with --v (verbose) or --vv (debug) for more details
Error: [PostgreSQL error] failed to retrieve server_version_num: connection refused

  Run with --v (verbose) or --vv (debug) for more details
Error: [PostgreSQL error] failed to retrieve server_version_num: connection refused

  Run with --v (verbose) or --vv (debug) for more details
Error: [PostgreSQL error] failed to retrieve server_version_num: connection refused

  Run with --v (verbose) or --vv (debug) for more details
Error: [PostgreSQL error] failed to retrieve server_version_num: connection refused

  Run with --v (verbose) or --vv (debug) for more details
Error: [PostgreSQL error] failed to retrieve server_version_num: connection refused

  Run with --v (verbose) or --vv (debug) for more details
Error: [PostgreSQL error] failed to retrieve server_version_num: connection refused

  Run with --v (verbose) or --vv (debug) for more details
Bootstrapping database...
migrating core on database 'kong'...
core migrated up to: 000_base (executed)
core migrated up to: 001_14_to_15 (executed)
core migrated up to: 002_15_to_1 (executed)
core migrated up to: 003_100_to_110 (executed)
core migrated up to: 004_110_to_120 (executed)
migrating hmac-auth on database 'kong'...
hmac-auth migrated up to: 000_base_hmac_auth (executed)
hmac-auth migrated up to: 001_14_to_15 (executed)
migrating oauth2 on database 'kong'...
oauth2 migrated up to: 000_base_oauth2 (executed)
oauth2 migrated up to: 001_14_to_15 (executed)
oauth2 migrated up to: 002_15_to_10 (executed)
migrating jwt on database 'kong'...
jwt migrated up to: 000_base_jwt (executed)
jwt migrated up to: 001_14_to_15 (executed)
migrating basic-auth on database 'kong'...
basic-auth migrated up to: 000_base_basic_auth (executed)
basic-auth migrated up to: 001_14_to_15 (executed)
migrating key-auth on database 'kong'...
key-auth migrated up to: 000_base_key_auth (executed)
key-auth migrated up to: 001_14_to_15 (executed)
migrating acl on database 'kong'...
acl migrated up to: 000_base_acl (executed)
acl migrated up to: 001_14_to_15 (executed)
migrating response-ratelimiting on database 'kong'...
response-ratelimiting migrated up to: 000_base_response_rate_limiting (executed)
response-ratelimiting migrated up to: 001_14_to_15 (executed)
response-ratelimiting migrated up to: 002_15_to_10 (executed)
migrating rate-limiting on database 'kong'...
rate-limiting migrated up to: 000_base_rate_limiting (executed)
rate-limiting migrated up to: 001_14_to_15 (executed)
rate-limiting migrated up to: 002_15_to_10 (executed)
rate-limiting migrated up to: 003_10_to_112 (executed)
25 migrations processed
25 executed
Database is up-to-date
Database already bootstrapped

**Comment by hutchic** [comment]
It is advisable to run the migrations in their own ephemeral container

docker-compose v2: https://github.com/Kong/docker-kong/blob/master/compose/docker-compose.yml
docker-compose v3: https://github.com/Kong/docker-kong/blob/master/swarm/docker-compose.yml

If you wish to run them all in a single container make your own Dockerfile `FROM Kong` and add a custom `entrypoint.sh`
