### ISSUE TITLE
mapping uri with service in nginx config

### ISSUE THREAD

**Issue by tungts1101** [Kong/docker-kong#277]
Could you give an example of how to write a mapping URI with my own service, suppose a _feed_ service runs on 10.0.0.1 and _register_ runs on 10.0.0.2? One more thing, even though README states that kong will run on nginx-lb but I can't see nginx anywhere in docker-compose.yml. Did I mistake any concept of docker?

**Comment by jf-delineate** [comment]
I also observed this and it has been resolved in #533

**Comment by gszr** [comment]
The support for Swarm - and consequently nginx-lb - was removed. We adjusted the docs to reflect that.
