### ISSUE TITLE
docker kong:1.3.0rc1 is error

### ISSUE THREAD

**Issue by duzhenxun** [Kong/docker-kong#282]
docker pull kong:1.3.0rc1

docker logs kong
2019/08/01 10:55:30 [error] 1#0: init_by_lua error: /usr/local/share/lua/5.1/kong/cmd/utils/migrations.lua:25: New migrations available; run 'kong migrations up' to proceed
stack traceback:
	[C]: in function 'error'
	/usr/local/share/lua/5.1/kong/cmd/utils/migrations.lua:25: in function 'check_state'
	/usr/local/share/lua/5.1/kong/init.lua:316: in function 'init'
	init_by_lua:3: in main chunk
nginx: [error] init_by_lua error: /usr/local/share/lua/5.1/kong/cmd/utils/migrations.lua:25: New migrations available; run 'kong migrations up' to proceed
stack traceback:
	[C]: in function 'error'
	/usr/local/share/lua/5.1/kong/cmd/utils/migrations.lua:25: in function 'check_state'
	/usr/local/share/lua/5.1/kong/init.lua:316: in function 'init'
	init_by_lua:3: in main chunk

**Comment by hutchic** [comment]
Per the docker-compose examples in this repository if you're upgrading from an earlier version of Kong run `kong migrations up`

https://github.com/Kong/docker-kong/blob/289821cd95a938be2abe72508c1cea624e9651c7/compose/docker-compose.yml#L26-L42

https://github.com/Kong/docker-kong/blob/289821cd95a938be2abe72508c1cea624e9651c7/swarm/docker-compose.yml#L26-L40

**Comment by farisjr** [comment]
I have this issue with this logs on docker, any idea whats going on? i try follow some advice from stackoverflow but cant solved this problem

[error] 1#0: init_by_lua error: /usr/local/share/lua/5.1/kong/cmd/utils/migrations.lua:20: New migrations available; run 'kong migrations up' to proceed
stack traceback:
[C]: in function 'error'
/usr/local/share/lua/5.1/kong/cmd/utils/migrations.lua:20: in function 'check_state'
/usr/local/share/lua/5.1/kong/init.lua:450: in function 'init'
init_by_lua:3: in main chunk
nginx: [error] init_by_lua error: /usr/local/share/lua/5.1/kong/cmd/utils/migrations.lua:20: New migrations available; run 'kong migrations up' to proceed
stack traceback:
[C]: in function 'error'
/usr/local/share/lua/5.1/kong/cmd/utils/migrations.lua:20: in function 'check_state'
/usr/local/share/lua/5.1/kong/init.lua:450: in function 'init'
init_by_lua:3: in main chunk
