### ISSUE TITLE
Resource Not found exception in Mac

### ISSUE THREAD

**Issue by AnithaRajamuthu** [Kong/docker-kong#286]
Hi ,

 I have cloned git project from below link,
https://github.com/Kong/docker-kong.git

Executed docker-compose up command - below is the terminal output.

rajamuthua-a01:compose rajamuthua$ docker-compose up
Starting compose_db_1 ... done
Starting compose_kong-migrations-up_1 ... done
Starting compose_kong-migrations_1    ... done
Starting compose_kong_1               ... done
Attaching to compose_db_1, compose_kong-migrations-up_1, compose_kong-migrations_1, compose_kong_1
db_1                  | LOG:  database system was interrupted; last known up at 2019-08-09 13:33:39 UTC
db_1                  | LOG:  database system was not properly shut down; automatic recovery in progress
db_1                  | LOG:  invalid record length at 0/187BAB0
db_1                  | LOG:  redo is not required
db_1                  | LOG:  MultiXact member wraparound protections are now enabled
db_1                  | LOG:  database system is ready to accept connections
db_1                  | LOG:  autovacuum launcher started
kong-migrations-up_1  | Database is already up-to-date
kong-migrations_1     | Database already bootstrapped
kong_1                | 2019/08/09 13:50:19 [notice] 1#0: using the "epoll" event method
kong_1                | 2019/08/09 13:50:19 [notice] 1#0: openresty/1.13.6.2
kong_1                | 2019/08/09 13:50:19 [notice] 1#0: built by gcc 8.3.0 (Alpine 8.3.0) 
kong_1                | 2019/08/09 13:50:19 [notice] 1#0: OS: Linux 4.9.125-linuxkit
kong_1                | 2019/08/09 13:50:19 [notice] 1#0: getrlimit(RLIMIT_NOFILE): 1048576:1048576
kong_1                | 2019/08/09 13:50:19 [notice] 1#0: start worker processes
kong_1                | 2019/08/09 13:50:19 [notice] 1#0: start worker process 33
kong_1                | 2019/08/09 13:50:19 [notice] 1#0: start worker process 34
kong_1                | 2019/08/09 13:50:19 [notice] 1#0: start worker process 35
kong_1                | 2019/08/09 13:50:19 [notice] 1#0: start worker process 36
kong_1                | 2019/08/09 13:50:19 [notice] 33#0: *1 [lua] cache_warmup.lua:42: cache_warmup_single_entity(): Preloading 'services' into the cache ..., context: init_worker_by_lua*
kong_1                | 2019/08/09 13:50:19 [notice] 33#0: *1 [lua] cache_warmup.lua:81: cache_warmup_single_entity(): finished preloading 'services' into the cache (in 0ms), context: init_worker_by_lua*
kong_1                | 2019/08/09 13:50:19 [notice] 33#0: *1 [lua] cache_warmup.lua:42: cache_warmup_single_entity(): Preloading 'plugins' into the cache ..., context: init_worker_by_lua*
kong_1                | 2019/08/09 13:50:19 [notice] 33#0: *1 [lua] cache_warmup.lua:81: cache_warmup_single_entity(): finished preloading 'plugins' into the cache (in 0ms), context: init_worker_by_lua*
compose_kong-migrations-up_1 exited with code 0

Exception faced "Resource Not found"
rajamuthua-a01:compose rajamuthua$ http :8001/apis
HTTP/1.1 404 Not Found
Access-Control-Allow-Origin: *
Connection: keep-alive
Content-Length: 23
Content-Type: application/json; charset=utf-8
Date: Fri, 09 Aug 2019 13:58:41 GMT
Server: kong/1.2.1

{
    "message": "Not found"
}

Kindly assist.
Thanks

**Comment by hutchic** [comment]
The `/apis` endpoint has been deprecated / removed since 0.14. If you want to build / run older versions of Kong via the docker compose `export KONG_DOCKER_TAG=0.13` should handle that
