### ISSUE TITLE
Run migration for custom plugins with docker image

### ISSUE THREAD

**Issue by umarhussain15** [Kong/docker-kong#293]
I'm adding a custom plugins to docker image which also need to interact with database.
I added a migration folder in my plugin as kong docs specified. Then while running the docker image I provide my custom plugin in config and as well as path for custom plugin (I'm also mounting the plugin folder inside docker at /plugins)

`KONG_LUA_PACKAGE_PATH=/plugins/?.lua;/plugins/?/init.lua;`

Now the docker stops due to error thrown by kong which says that new migration is present please run `kong migrations up`.

Now I'm stuck on how to run migration of custom plugin before starting the docker container, since after starting the container kong will only know about the custom plugin via package path.

Is there anything I'm missing to add migrations of custom plugins so that db is prepared before kong starts?

**Comment by Tieske** [comment]
How do you start the container?

If you add the custom plugin, and then initialize your Kong enviornment as per instructions with "kong migrations bootstrap" or "kong migrations up" it should run the migrations, after which you can start kong

**Comment by umarhussain15** [comment]
I have plugin directory in home folder of the host and then I'm running this command to start the docker.

```docker run -d --name kong --network=kong-net \ 
-e "KONG_DATABASE=postgres" -e "KONG_PG_HOST=kong-database"  \
-e "KONG_LUA_PACKAGE_PATH=/plugins/?.lua;/plugins/?/init.lua;"  \
-v "/home/user/plugins:/plugins" \
-v "/home/user/kong:/etc/kong" \
-e "KONG_PROXY_ACCESS_LOG=/dev/stdout"  \
-e "KONG_ADMIN_ACCESS_LOG=/dev/stdout"  \
-e "KONG_PROXY_ERROR_LOG=/dev/stderr"  \
-e "KONG_ADMIN_ERROR_LOG=/dev/stderr" \
-e "KONG_ADMIN_LISTEN=0.0.0.0:8001, 0.0.0.0:8444 ssl" \
-p 8000:8000      -p 8443:8443      -p 8001:8001      -p 8444:8444  \
kong:latest
```

And my kong.conf file contains this:

```
plugins = bundled,key-auth-encrypted

custom_plugins = key-auth-encrypted
```
The issue is I cannot add plugin  until the container of docker is not running. But after container starts it throws error that there is a new migration and I need to run kong migration. After this container exits.

Now kong migration doesn't know about my plugin since its present in container's host. This is where I'm stuck how to tell kong migrations that plugin is not inside container yet (since container failed to start earlier) but I need to run plugin's migrations before starting kong.

**Comment by Tieske** [comment]
have a look at: https://github.com/Kong/docker-kong/tree/master/customize

**Comment by Tieske** [comment]
@umarhussain15 any update?

**Comment by umarhussain15** [comment]
Hi @Tieske , I stopped working on the project shortly after this issue at my previous job. So I have no update on the solution.
I will close this issue now.
