### ISSUE TITLE
http2

### ISSUE THREAD

**Issue by lukasa1993** [Kong/docker-kong#295]
what is best way to enable http2 in `docker-compose.yml` ? 

```KONG_PROXY_LISTEN=0.0.0.0:80 http2, 0.0.0.0:443 ssl http2```
tried this in env file but kong doesn't start if its there

**Comment by lukasa1993** [comment]
@hutchic any idea?

**Comment by hutchic** [comment]
Sorry for the delay

I tried the following and it seems to work
```
git diff
diff --git a/compose/docker-compose.yml b/compose/docker-compose.yml
index fd5939c..52c14bf 100644
--- a/compose/docker-compose.yml
+++ b/compose/docker-compose.yml
@@ -50,6 +50,7 @@ services:
       KONG_ADMIN_ACCESS_LOG: /dev/stdout
       KONG_ADMIN_ERROR_LOG: /dev/stderr
       KONG_ADMIN_LISTEN: '0.0.0.0:8001'
+      KONG_PROXY_LISTEN: '0.0.0.0:8000 http2, 0.0.0.0:8443 ssl http2'
       KONG_CASSANDRA_CONTACT_POINTS: db
       KONG_DATABASE: postgres
       KONG_PG_DATABASE: ${KONG_PG_DATABASE:-kong}
```

Try changing `kong start` to `kong start -vv` lets see if there's an error message

**Comment by OneideLuizSchneider** [comment]
Hi @lukasa1993 
I had the same problem, I solve this by just add the root user in the docker run command.
For example:
`docker run --name kong \
     --network=kong-net \
     -e "KONG_DATABASE=postgres" \
     -e "KONG_PG_HOST=kong-database" \
     -e "KONG_PG_PASSWORD=123456" \
     -e "KONG_CASSANDRA_CONTACT_POINTS=kong-database" \
     -e "KONG_PROXY_ACCESS_LOG=/dev/stdout" \
     -e "KONG_ADMIN_ACCESS_LOG=/dev/stdout" \
     -e "KONG_PROXY_ERROR_LOG=/dev/stderr" \
     -e "KONG_ADMIN_ERROR_LOG=/dev/stderr" \
     -e "KONG_ADMIN_LISTEN=0.0.0.0:8001, 0.0.0.0:8444 ssl" \
     -e "KONG_PROXY_LISTEN=0.0.0.0:80, 0.0.0.0:443 ssl" \
     -p 80:80 \
     -p 443:443 \
     -p 8001:8001 \
     -p 8444:8444 \
     -p 9542:9542 \
     #root user
     --user "0" \
     kong:latest`

**Comment by gszr** [comment]
@OneideLuizSchneider As you were changing the port to 80, it had to be run in privileged mode. An alternative is to leave the default port and map it to 80 (`-p 8000:80`). Closing the issue, feel free to reopen if needed!
