### ISSUE TITLE
ModSecurity for Kong

### ISSUE THREAD

**Issue by meniem** [Kong/docker-kong#300]
Hi,

We have kong version 0.14.1 based on the below images:
https://github.com/Kong/docker-kong/tree/master/ubuntu

I'm wondering how can I implement **Modsecurity** WAF on top of Kong's **OpenResty for Nginx**.

I have installed ModSecurity, and complied the same OpenResty version that exist on the kong image, and then I configured Nginx associated with Openresty for ModSecurity. But I'm missing the part of configuring Kong's Nginx so that all the API requests go through it.

For example, I have a rule to prevent the word "**testwaf**" when running a curl command as below:

**curl localhost?testparam=testwaf** --> 403 forbidden

How can I do the sam for the API requests:

**curl localhost:8001?testparam=testwaf** 
**curl localhost:8000?testparam=testwaf** 

The Nginx file I configured is:
**/usr/local/openresty/nginx/conf/nginx-modsec.conf**

while the file Nginx files under Kong directory are:
**/usr/local/kong/nginx.conf
/usr/local/kong/nginx-kong.conf**

I used: **export KONG_NGINX_HTTP_INCLUDE="/usr/local/openresty/nginx/conf/nginx-modsec.conf"** to include it to kong, but didn't work for api links.

**Comment by p0pr0ck5** [comment]
Hi,

I would advise against trying to use modsecurity with kong. The two do not integrate, and you will lose a lot of kong functionality when modsecurity executes a blocking action (and vice versa). Also, the modsecurity module for nginx has a detrimental impact on performance and I would strongly advocate against running it in production.

There is an open Kong issue for a WAF plugin feature request (https://github.com/Kong/kong/issues/1048), FYI. But even if we chose to build something like that someday it will never be a modsecurity integration

**Comment by flybyray** [comment]
> ... But even if we chose to build something like that someday it will never be a modsecurity integration

Do you have experience with nginx plus? why they choose to integrate ModSecurity? https://www.nginx.com/blog/modsecurity-waf-released/ 

I know you are the author of https://github.com/p0pr0ck5/lua-resty-waf and maybe your opinion is biased.
The project states
> lua-resty-waf is currently in active development
where is this development? is it in this redux branch ? see: https://github.com/p0pr0ck5/lua-resty-waf/branches 

ModSecurity has a lot of fine documentation and tooling.
Maybe this is why lua-resty-waf tries to mimic ModSecurity. But it's not one.
If you have special application requirements upstream, you need to have tools to configure and modify the rules.
see: https://www.netnea.com/cms/apache-tutorial-8_handling-false-positives-modsecurity-core-rule-set/
even if those guides just show how it works for apache ( maybe for nginx plus too) you can see how useful the workflows are to handle false positives for example.

**Comment by fabiot100** [comment]
Hello!
Searching a lot, I've done that combination, kong with modsecurity. I've created a documentation on my github, so follow the link:

https://github.com/fabiot100/DevOps/tree/master/kong

**Comment by phucnv282** [comment]
> Hello! Searching a lot, I've done that combination, kong with modsecurity. I've created a documentation on my github, so follow the link:
> 
> https://github.com/fabiot100/DevOps/tree/master/kong

hi @fabiot100, the URL is not found, can you reup it, please

**Comment by fabiot100** [comment]
Hey @phucnv282 ,
My repository was private because I was making some changes, but now it's public and you can now access it.

**Comment by fabiot100** [comment]
> Hi,
> I have already integrated ModSecurity with Kong
> Currently, ModSecurity is enabled for all services/routes. Have the way to config ModSecurity for each service/route (like some Kong plugins)???

Sorry man, I don't know if this is possible. If you discover how, post it here, please?

I have modsec activated in the company I work, but it is in detection mode yet. I'll have to work on this in the future 😅

**Comment by phucnv282** [comment]
Hmm, it's a hard problem :(
And I saw that the image after installing ModSecurity is very large, how can I reduce its size???

**Comment by fabiot100** [comment]
> Hmm, it's a hard problem :(
> And I saw that the image after installing ModSecurity is very large, how can I reduce its size???

I think you can't. Modsec must to be installed and, after that, the size is a little bit large.

**Comment by phucnv282** [comment]
hi @fabiot100 ,
currently, I realized that ModSecurity doesn't log anything
this is my config
```
SecRuleEngine On
# SecRuleEngine DetectionOnly
Include /usr/local/kong/modsec/rules/*.conf
SecRequestBodyAccess On
SecAuditLog /var/log/modsecurity_audit.log
# SecAuditLog /dev/stdout
SecAuditLogParts ABCEFH
SecAuditEngine RelevantOnly
```
earlier, I configured `SecRuleEngine On` so Kong logs to stdout when a request is blocked.
![Screenshot from 2022-07-27 13-54-06](https://user-images.githubusercontent.com/33126800/181181382-c7ab8d05-29d9-45fb-b101-4dc109406cfe.png)
but now I switch to DetectionOnly mode and I can't find ModSecurity logs
do you faced with this problem?

**Comment by fabiot100** [comment]
> 

Hi, @phucnv282 

Below are my settings:

`# -- Audit log configuration -------------------------------------------------

SecAuditEngine RelevantOnly
SecAuditLogRelevantStatus "^(?:5|4(?!04))"

SecAuditLogParts AIHZ

SecAuditLogType Serial
SecAuditLog /var/log/modsec/modsec_audit.log


# -- Rule engine initialization ----------------------------------------------
SecRuleEngine On


Note that SecAuditLog, in my compose, is mapped as a volume.
And at the log you put here, if you see, there are two things: warning and denied. The warning section you will se what is effectively being blocked. The denied section you will se the rule that blocks that warning. So, if you want to allow that warning and, consequently, not blocking, create the file /usr/local/coreruleset/rules/RESPONSE-999-EXCLUSION-RULES-AFTER-CRS.conf and add to it the ID reported in the warning message, like the following example:
![image](https://user-images.githubusercontent.com/79455498/181248829-41c227a4-6c11-462a-8e0a-413ab2e6ae2a.png)

**Comment by phucnv282** [comment]
After comparing my settings to yours, I think my settings are correct
I also add DebugLog for further information
Fortunately, DebugLog works and I get an error `[165892908576.975713] [/?exec=/bin/bash] [1] Cannot save the audit log: Log path is not valid.`
![Screenshot from 2022-07-27 20-43-00](https://user-images.githubusercontent.com/33126800/181262639-bc08cd04-f6ab-4591-b635-5b137d656cd9.png)
I don't know what makes the `SecAuditLog /usr/local/kong/logs/modsec` be invalid while SecDebugLog is still working :((

**Comment by phucnv282** [comment]
I tried some modifications, ModSecurity is using `SecAuditLog /var/log/modsec_audit.log` in recommended .conf file
If I change it to another location, the SecDebugLog will raise the error `Log path is not valid`
I rebuild the image without updating that path, bum, it WORKS :))

Then, I override it by adding `SecAuditLog /usr/local/kong/logs/modsec/audit.log` to the Nginx config but it doesn't affect, ModSecurity still writes log to `/var/log/modsec_audit`. Why?

**Comment by fabiot100** [comment]
> I tried some modifications, ModSecurity is using `SecAuditLog /var/log/modsec_audit.log` in recommended .conf file
> If I change it to another location, the SecDebugLog will raise the error `Log path is not valid`
> I rebuild the image without updating that path, bum, it WORKS :))
> 
> Then, I override it by adding `SecAuditLog /usr/local/kong/logs/modsec/audit.log` to the Nginx config but it doesn't affect, ModSecurity still writes log to `/var/log/modsec_audit`. Why?

How are you changing that settings? Directly in the container, or via volume?
Are you restarting your Kong container after that change?

**Comment by phucnv282** [comment]
Finally, I spot my wrong.
I misunderstand the `SecAuditLogType` directive, I forget to config it to `Serial` that really comes along with `SecAuditLog`

**Comment by fabiot100** [comment]
> Finally, I spot my wrong.
> I misunderstand the `SecAuditLogType` directive, I forget to config it to `Serial` that really comes along with `SecAuditLog`

Ahh, perfect! In the beginning I made that confusion too hahahaha

**Comment by phucnv282** [comment]
hi @fabiot100,
recently, I apply Kong-ModSecurity onto Prod env, and I have a problem with performance.
I saw that the CPU of Kong pods significantly increase, and the latency of requests does too, so I must disable it.
Do you face a similar problem? If yes, how do you tune your Kong/ModSecurity?

**Comment by fabiot100** [comment]
> hi @fabiot100,
> recently, I apply Kong-ModSecurity onto Prod env, and I have a problem with performance.
> I saw that the CPU of Kong pods significantly increase, and the latency of requests does too, so I must disable it.
> Do you face a similar problem? If yes, how do you tune your Kong/ModSecurity?
> 
> Update: I need SecAuditEngine On for alert when requests trigger rules :)

Hi, @phucnv282 

I don't. I have modsec implemented only in sandbox and homolog, for now. But, if it helps, I didn't have that issue in my environments. And I have a lots of requests that pass through my modsec. Maybe can be because the option SecAuditEngine On? For me I put that in RelevantOnly.

**Comment by phucnv282** [comment]
hi @fabiot100 ,
I already have updated SecAuditEngine to RelevantOnly but the latency is still quite high.
I built my image like your repo.
Can I have your full ModSec configuration?

**Comment by fabiot100** [comment]
> hi @fabiot100 ,
> I already have updated SecAuditEngine to RelevantOnly but the latency is still quite high.
> I built my image like your repo.
> Can I have your full ModSec configuration?

Hi, @phucnv282 .
Sorry about answer you too late.
I don't have it to pass to you, but I ensure you, the only things I've changed were that I share here with you above.
I hope you can fix it. If you make it, please share here.
