### ISSUE TITLE
how to setting kong domain?

### ISSUE THREAD

**Issue by Millyn** [Kong/docker-kong#307]
now , use 192.168.1.1:8001 call on kong.

but i want use domain.com:8001 or domain.com call on kong;

how to setting?

thanks.

**Comment by hutchic** [comment]
Kong will respond to all requests that are directed to where you're running it on port `8001`. Setting up DNS to point `domain.com` is what's required or if this is for testing purposes modify your local domain resolution ie on Linux

```
cat /etc/hosts
192.168.1.1 domain.com
```
