### ISSUE TITLE
Entrypoint script does not account for non-standard prefixes

### ISSUE THREAD

**Issue by rainest** [Kong/docker-kong#313]
Speculation based on issues encountered running Kong with a non-standard prefix in Kubernetes. Observations from there:
- When using the standard `/usr/local/kong` prefix, all Kong containers run normally.
- Kong's Kubernetes initContainer, which runs a plain "kong start; kong stop", does not encounter any issues when using a non-standard prefix.
- Kong's primary Kubernetes container, which does run the "kong docker-start" entrypoint script command, fails due a permissions issue on .kong_env when using a non-standard prefix.

We prepare the prefix as the main container user at https://github.com/Kong/docker-kong/blob/1.4.2/centos/docker-entrypoint.sh#L15

We change ownership of `/usr/local/kong` to the dedicated Kong user at https://github.com/Kong/docker-kong/blob/1.4.2/centos/docker-entrypoint.sh#L33

We finally start Kong as the dedicated user at https://github.com/Kong/docker-kong/blob/1.4.2/centos/docker-entrypoint.sh#L34-L36

It stands to reason, then, that if we use a non-standard prefix and started the container as root (Kubernetes apparently ignores USER directives, and only honors its own runAsUser setting), that the non-standard prefix will remain owned by root, preventing Kong from accessing files under it with no world read permission.

**Comment by hutchic** [comment]
does the ability to set a custom kong prefix get around these challenges?

https://github.com/Kong/docker-kong/blob/2.0.4/alpine/docker-entrypoint.sh#L33

**Comment by rainest** [comment]
The chown and hardcoded path no longer exist in current master, so this should be all clear.
