### ISSUE TITLE
support for calling `ulimit` before launching kong inside container

### ISSUE THREAD

**Issue by hhromic** [Kong/docker-kong#314]
In a [recent change][1], Kong no longer upper-limits the `worker_connections` value to `16384` and instead now relies on the file limit information from `ulimit`. Quoting the PR:

>  There is no reason to set this cap; users should be able to rely on file limit information (as parsed by get_ulimit()) to define this value instead of silently being capped here.

However there isn't an easy/simple way to configure `ulimit` for the Kong container in Docker Swarm mode, resulting in [Kong using a high amount of memory][2]. To be clear, Docker compose files do have an `ulimits` directive but is not implemented for Docker Swarm mode at the moment.

Therefore to solve the problem, I propose the usage of an optional environment variable, e.g. `KONG_ULIMIT`, that contains arguments to pass to `ulimit` before starting Kong inside the container. If this environment variable is set to a non-empty value, then `docker-entrypoint.sh` should pass the value to `ulimit` and then launch Kong, something like this:
```sh
[[ -n $KONG_ULIMIT ]] && ulimit $KONG_ULIMIT  # this should not be quoted
exec su-exec kong [...]
```

The user then would be able to use `KONG_ULIMIT="-n 16384"` (or any desired value) to limit the amount of open files and thus bring down memory consumption of Kong workers.

What do you think?

[1]: https://github.com/Kong/kong/pull/5148
[2]: https://github.com/Kong/kong/issues/5324

**Comment by bungle** [comment]
As #5390 was merged, I will close this. The new upper cap is 65536. And you can even specify values of your own (e.g. override that `math.min("ulimit -n", 65536)`). That's why I am closing this.

**Comment by hhromic** [comment]
Thanks!

Just to understand correctly: an upper limit was re-introduced but now defaults to `65536` instead of `16384` and in addition this and other parameters can now be customised from configuration?

Looking forward for a release containing this change sooner than later :)
