### ISSUE TITLE
Kong 2.0 images not allowing to write to /usr/local/lib/luarocks/rocks-5.1

### ISSUE THREAD

**Issue by cleppanen** [Kong/docker-kong#328]
When trying to build with the latest versions of docker-kong, I get an error because the kong user can no longer write to the location specified in the error output. Below you'll see my Dockerfile and the error output from the `docker build` command. I have tried the tags `latest` `2.0.0` `2.0.0-alpine` and all give me the same error listed below.

Dockerfile
```terminal
FROM kong:latest

RUN luarocks install lua-resty-openidc
RUN luarocks install kong-oidc

COPY kong.conf /etc/kong/kong.conf
```

Error
```terminal
Error: Your user does not have write permissions in /usr/local/lib/luarocks/rocks-5.1 
-- you may want to run as a privileged user or use your local tree with --local.
```

Using version `1.5` does not cause this error, and we will probably use that in the interim until this can be addressed.

Thank you for your time.

**Comment by hutchic** [comment]
Whoops I meant to include that in the CHANGELOG / release notes. I'll make a note to document this somewhere official:

Going forward we're running Kong as the least privileged user possible so you'll need a `USER root` entry in your Dockerfile

```
FROM kong:latest

USER root

RUN luarocks install lua-resty-openidc
RUN luarocks install kong-oidc

USER kong
```

**Comment by cleppanen** [comment]
Thanks @hutchic
