### ISSUE TITLE
Zip package left in Docker Image

### ISSUE THREAD

**Issue by barrelmaker97** [Kong/docker-kong#333]
Going through the alpine Dockerfile, I noticed that the zip package is left in the image.
https://github.com/Kong/docker-kong/blob/7c6281ca1906b05080af23c94fafa2ff08d05856/alpine/Dockerfile#L13
Why is this? Is there a reason that zip is needed during runtime? If it can be safely removed, I can open a PR to remove it.

**Comment by barrelmaker97** [comment]
Actually, on closer inspection, build dependencies are not removed at all anymore. In the 1.5 Dockerfile, I can see the line `&& apk del .build-deps`, which is not present in the 2.0 Dockerfile.

**Comment by hutchic** [comment]
`zip` is necessary for folks to install Kong plugins or additional luarocks
```
luarocks install version
Warning: Failed searching manifest: Failed extracting manifest file: 'unzip -n' program not found. Make sure unzip is installed and is available in your PATH (or you may want to edit the 'variables.UNZIP' value in file '/usr/local/etc/luarocks/config-5.1.lua')
Installing https://raw.githubusercontent.com/rocks-moonscript-org/moonrocks-mirror/master/version-1.0.1-2.src.rock

Error: Failed unpacking rock file: /tmp/luarocks_luarocks-rock-version-1.0.1-2-5542175/version-1.0.1-2.src.rock: 'unzip -n' program not found. Make sure unzip is installed and is available in your PATH (or you may want to edit the 'variables.UNZIP' value in file '/usr/local/etc/luarocks/config-5.1.lua')
```

In a future version we may remove it and document that folks need to add zip, install their plugin, remove zip but enough people assume `zip` will be available we'd need to call it out as a breaking change

**Comment by barrelmaker97** [comment]
@hutchic Understandable, thanks for the clarification. It still does stand though that the `.build-deps` virtual package is not being uninstalled anymore as of Kong 2.0. Is this intentional?

**Comment by hutchic** [comment]
hm good question 👍. That may have been an omission

I have a PR https://github.com/Kong/docker-kong/pull/327 that's using docker builder pattern which IMO provides better protection against accidentally leaving unnecessary dependencies behind and should land shortly.

Do you have strong opinions if we should rebuild `2.0.1` after that lands so the additional packages aren't present? Alternatively wait for that PR to merge and build locally until `2.0.2` (or `2.1.0`)?

**Comment by barrelmaker97** [comment]
I'm fine with waiting, personally I'm still using Kong 1.5. Happy to wait until later versions of 2.0! Thanks for looking into this 👍
