### ISSUE TITLE
Kong Docker Customize: Custom plugin not available on Kong

### ISSUE THREAD

**Issue by xmcn2** [Kong/docker-kong#337]
Hi,

I have a problem trying to `customize` Kong from https://github.com/Kong/docker-kong/tree/master/customize.

I have a simple plugin that I'm trying to add to the docker image but this does not show up in Kong as `available_on_server`. The files exist on the docker container but they are still not showing up as available / enabled. I'm using the example.sh script provided in repo to create and install a custom Luarock.

The script executes successfully and packs / installs the rock to the docker image. I suppose the only difference might be that I'm using this custom image as Kong Ingress controller. I've tried setting the `KONG_PLUGINS=bundled, custom-plugin` environment variable in the ingress controller but this doesn't help.

What am I missing?

Any help will be greatly appreciated?

**Comment by Tieske** [comment]
is the plugin available if you run the image locally?

what version of Kong are you using? make sure to pull the latest version of the docker image for that Kong version.
