### ISSUE TITLE
#337 re-appeared in release 2.0.2

### ISSUE THREAD

**Issue by Tieske** [Kong/docker-kong#353]
see #317 
see #332
see https://github.com/Kong/docker-kong/pull/332#issuecomment-602386026 reported by @jeiwan

**Comment by Tieske** [comment]
@hutchic any ideas as to why this re-appeared?
Can we quickly rebuild the image for 2.0.2?

**Comment by hutchic** [comment]
![image](https://user-images.githubusercontent.com/697188/77919931-ccb98980-726b-11ea-9eb3-cc0108b60705.png)

It didn't merge in time to hit the 2.0.2 tag from the looks of it

**Comment by ariutk** [comment]
This issue remains unresolved in 2.0.3-alpine. A quick way to fix this redefine file /old-entrypoint.sh

-v /opt/kong/quick-fix-old-entrypoint.sh:/old-entrypoint.sh

What should change https://github.com/Kong/docker-kong/pull/332/commits/ad581684ec3410333de73bd6b78224135c3f8323

**Comment by hutchic** [comment]
Waiting on https://github.com/docker-library/official-images/pull/7880 then I'll backport this and a few other fixes.

**Comment by hutchic** [comment]
this should be resolved and available in `Kong:2.0.4`
