### ISSUE TITLE
Fix pg password errors when launching via docker compose

### ISSUE THREAD

**Issue by hellojustin** [Kong/docker-kong#358]
Hiya Kong Team!

I pulled this repo tonight and quickly ran into some issues when trying to launch the services defined in `compose/docker-compose.yml`. After a little debugging, I realized that this is due to the names of some environment variables defined in that file. I'd love to submit a tiny PR that fixes the issue.

Here's more detail about the situation:

At the current master sha (`b6fed1072fae589543f71a1bd92dbde880a61850`), `docker-compose up` fails to launch all but the `db` container, with errors that look like this:

```
kong-migrations_1     | Error: missing password, required for connect
kong-migrations_1     |
kong-migrations_1     |   Run with --v (verbose) or --vv (debug) for more details
compose_kong-migrations_1 exited with code 1
```

```
kong-migrations-up_1  | Error: missing password, required for connect
kong-migrations-up_1  |
kong-migrations-up_1  |   Run with --v (verbose) or --vv (debug) for more details
compose_kong-migrations-up_1 exited with code 1
```

```
kong_1                | 2020/04/15 05:19:21 [error] 1#0: init_by_lua error: /usr/local/share/lua/5.1/pgmoon/init.lua:271: missing password, required for connect
kong_1                | stack traceback:
kong_1                | 	[C]: in function 'assert'
kong_1                | 	/usr/local/share/lua/5.1/pgmoon/init.lua:271: in function 'auth'
kong_1                | 	/usr/local/share/lua/5.1/pgmoon/init.lua:211: in function 'connect'
kong_1                | 	.../share/lua/5.1/kong/db/strategies/postgres/connector.lua:202: in function 'connect'
kong_1                | 	.../share/lua/5.1/kong/db/strategies/postgres/connector.lua:489: in function 'query'
kong_1                | 	.../share/lua/5.1/kong/db/strategies/postgres/connector.lua:270: in function 'init'
kong_1                | 	/usr/local/share/lua/5.1/kong/db/init.lua:138: in function 'init_connector'
kong_1                | 	/usr/local/share/lua/5.1/kong/init.lua:389: in function 'init'
kong_1                | 	init_by_lua:3: in main chunk
kong_1                | nginx: [error] init_by_lua error: /usr/local/share/lua/5.1/pgmoon/init.lua:271: missing password, required for connect
kong_1                | stack traceback:
kong_1                | 	[C]: in function 'assert'
kong_1                | 	/usr/local/share/lua/5.1/pgmoon/init.lua:271: in function 'auth'
kong_1                | 	/usr/local/share/lua/5.1/pgmoon/init.lua:211: in function 'connect'
kong_1                | 	.../share/lua/5.1/kong/db/strategies/postgres/connector.lua:202: in function 'connect'
kong_1                | 	.../share/lua/5.1/kong/db/strategies/postgres/connector.lua:489: in function 'query'
kong_1                | 	.../share/lua/5.1/kong/db/strategies/postgres/connector.lua:270: in function 'init'
kong_1                | 	/usr/local/share/lua/5.1/kong/db/init.lua:138: in function 'init_connector'
kong_1                | 	/usr/local/share/lua/5.1/kong/init.lua:389: in function 'init'
kong_1                | 	init_by_lua:3: in main chunk
compose_kong_1 exited with code 1
```

I believe the services - including the db itself - are not receiving a db password via the environment variables. I looked at the docker [compose syntax doc around secrets](https://docs.docker.com/compose/compose-file/#secrets), as well as the docs for the [`postgres` image](https://hub.docker.com/_/postgres) and [`kong` image](https://hub.docker.com/_/kong), and determined that the password environment variable names shouldn't end with `_FILE`.

With the following changes, `docker-compose up` seems to launch the services as intended:

```diff
diff --git a/compose/docker-compose.yml b/compose/docker-compose.yml
index de946b8..4fb761e 100644
--- a/compose/docker-compose.yml
+++ b/compose/docker-compose.yml
@@ -18,7 +18,7 @@ services:
       KONG_PG_DATABASE: ${KONG_PG_DATABASE:-kong}
       KONG_PG_HOST: db
       KONG_PG_USER: ${KONG_PG_USER:-kong}
-      KONG_PG_PASSWORD_FILE: /run/secrets/kong_postgres_password
+      KONG_PG_PASSWORD: /run/secrets/kong_postgres_password
     secrets:
       - kong_postgres_password
     networks:
@@ -38,7 +38,7 @@ services:
       KONG_PG_DATABASE: ${KONG_PG_DATABASE:-kong}
       KONG_PG_HOST: db
       KONG_PG_USER: ${KONG_PG_USER:-kong}
-      KONG_PG_PASSWORD_FILE: /run/secrets/kong_postgres_password
+      KONG_PG_PASSWORD: /run/secrets/kong_postgres_password
     secrets:
       - kong_postgres_password
     networks:
@@ -64,7 +64,7 @@ services:
       KONG_PG_USER: ${KONG_PG_USER:-kong}
       KONG_PROXY_ACCESS_LOG: /dev/stdout
       KONG_PROXY_ERROR_LOG: /dev/stderr
-      KONG_PG_PASSWORD_FILE: /run/secrets/kong_postgres_password
+      KONG_PG_PASSWORD: /run/secrets/kong_postgres_password
     secrets:
       - kong_postgres_password
     networks:
@@ -83,13 +83,13 @@ services:
     deploy:
       restart_policy:
         condition: on-failure
   db:
     image: postgres:9.5
     environment:
       POSTGRES_DB: ${KONG_PG_DATABASE:-kong}
       POSTGRES_USER: ${KONG_PG_USER:-kong}
-      POSTGRES_PASSWORD_FILE: /run/secrets/kong_postgres_password
+      POSTGRES_PASSWORD: /run/secrets/kong_postgres_password
     secrets:
       - kong_postgres_password
     healthcheck:
```

Happy to submit this change as a PR.

-Justin

**Comment by hellojustin** [comment]
Ah - hmm - I see what I _actually_ did here. Just set the password to `/run/secrets/kong_postgres_password`.. I don't believe it's reading from the file anymore..

**Comment by jazztong** [comment]
hi @hellojustin , I come to the same problem and realize kong still not support reading from file yet https://github.com/Kong/docker-kong/issues/91, hope it helps.

**Comment by hellojustin** [comment]
Thanks @jazztong - yeah, reading from secrets files seems to work for `postgres:9.5` but not for `kong:latest`, which I believe points to `kong:alpine-2.0.3`. That image was released 6 days ago, which should include the changes from https://github.com/Kong/docker-kong/pull/348/files, which seems to be the PR where support for reading secrets files was added.. So I'm a little stumped still. Going back to plain-old env vars for now!

**Comment by hutchic** [comment]
We had some challenges such that the official docker image builder wasn't appreciative of how we setup our Dockerfiles. As a result the docker-compose in master was dependent on a feature that never made it to the official images.

That should be resolved as of 2.0.4 ( https://github.com/docker-library/official-images/pull/7880 ) and I will backport the fix to 2.0.3.

In the meantime our unofficial docker images will work in a pinch https://hub.docker.com/repository/docker/kong/kong/tags?page=1

**Comment by thanhtai9606** [comment]
I have the same problems with password. Are there any wrong?? how to fix it???

`kong-migrations_1     |
kong-migrations_1     |   Run with --v (verbose) or --vv (debug) for more details
compose_kong-migrations_1 exited with code 1
kong-migrations-up_1  | Error: missing password, required for connect
kong-migrations-up_1  |
kong-migrations-up_1  |   Run with --v (verbose) or --vv (debug) for more details
compose_kong-migrations-up_1 exited with code 1
kong_1                | 2020/04/28 02:19:05 [error] 1#0: init_by_lua error: /usr/local/share/lua/5.1/pgmoon/init.lua:271: missing password, required for connect
kong_1                | stack traceback:
kong_1                |         [C]: in function 'assert'
kong_1                |         /usr/local/share/lua/5.1/pgmoon/init.lua:271: in function 'auth'
kong_1                |         /usr/local/share/lua/5.1/pgmoon/init.lua:211: in function 'connect'
kong_1                |         .../share/lua/5.1/kong/db/strategies/postgres/connector.lua:205: in function 'connect'
kong_1                |         .../share/lua/5.1/kong/db/strategies/postgres/connector.lua:492: in function 'query'
kong_1                |         .../share/lua/5.1/kong/db/strategies/postgres/connector.lua:273: in function 'init'
kong_1                |         /usr/local/share/lua/5.1/kong/db/init.lua:138: in function 'init_connector'
kong_1                |         /usr/local/share/lua/5.1/kong/init.lua:388: in function 'init'
kong_1                |         init_by_lua:3: in main chunk
kong_1                | nginx: [error] init_by_lua error: /usr/local/share/lua/5.1/pgmoon/init.lua:271: missing password, required for connect
kong_1                | stack traceback:
kong_1                |         [C]: in function 'assert'
kong_1                |         /usr/local/share/lua/5.1/pgmoon/init.lua:271: in function 'auth'
kong_1                |         /usr/local/share/lua/5.1/pgmoon/init.lua:211: in function 'connect'
kong_1                |         .../share/lua/5.1/kong/db/strategies/postgres/connector.lua:205: in function 'connect'
kong_1                |         .../share/lua/5.1/kong/db/strategies/postgres/connector.lua:492: in function 'query'
kong_1                |         .../share/lua/5.1/kong/db/strategies/postgres/connector.lua:273: in function 'init'
kong_1                |         /usr/local/share/lua/5.1/kong/db/init.lua:138: in function 'init_connector'
kong_1                |         /usr/local/share/lua/5.1/kong/init.lua:388: in function 'init'
kong_1                |         init_by_lua:3: in main chunk
`

**Comment by hutchic** [comment]
While waiting for Docker to merge / build 2.0.4 you can follow the docker-compose from the 2.0.2 tag https://github.com/Kong/docker-kong/tree/2.0.2/compose

**Comment by hutchic** [comment]
I've triple checked the `2.0.4` image works with the docker secret supplied password per out `docker-compose` file.
