### ISSUE TITLE
How to upgrade version of a bundled prometheus plugin for an image?

### ISSUE THREAD

**Issue by fighterleslie** [Kong/docker-kong#362]
Hi,

We're using Kong 1.4.2 docker image (alpine), which has a bundled plugin "kong-prometheus-plugin". The version of bundled plugin is 0.6.0

If I inspect a running docker container, in the file `/usr/local/lib/luarocks/rocks-5.1/kong/1.4.2-0/kong-1.4.2-0.rockspec`, there is a line says:

```
"kong-prometheus-plugin ~> 0.6",
```

The predefined metrics of this version cannot satisfy out need, we need to add more custom metrics. Several days ago, the plugin has a new version (0.8.0) which exposes the `prometheus` object for custom metrics. This is wonderful, but I'm wondering how to upgrade the plugin version from 0.6.0 to 0.8.0 for kong:1.4.2 image.

As per the Dockerfile of the kong:1.4.2 image:

```
FROM alpine:3.10
LABEL maintainer="Kong Core Team <team-core@konghq.com>"

ENV KONG_VERSION 1.4.2
ENV KONG_SHA256 edf917d956d697abb70f5f3f630d420ee699c6428bf953221cd8548eda490dcf


RUN adduser -Su 1337 kong \
	&& mkdir -p "/usr/local/kong" \
	&& apk add --no-cache --virtual .build-deps curl wget tar ca-certificates \
	&& apk add --no-cache libgcc openssl pcre perl tzdata libcap su-exec zip \
	&& wget -O kong.tar.gz "https://bintray.com/kong/kong-alpine-tar/download_file?file_path=kong-$KONG_VERSION.amd64.apk.tar.gz" \
	&& echo "$KONG_SHA256 *kong.tar.gz" | sha256sum -c - \
	&& tar -xzf kong.tar.gz -C /tmp \
	&& rm -f kong.tar.gz \
	&& cp -R /tmp/usr / \
	&& rm -rf /tmp/usr \
	&& cp -R /tmp/etc / \
	&& rm -rf /tmp/etc \
	&& apk del .build-deps \
	&& chown -R kong:0 /usr/local/kong \
	&& chmod -R g=u /usr/local/kong

COPY docker-entrypoint.sh /docker-entrypoint.sh

ENTRYPOINT ["/docker-entrypoint.sh"]

EXPOSE 8000 8443 8001 8444

STOPSIGNAL SIGQUIT

CMD ["kong", "docker-start"]

```

the file `/usr/local/lib/luarocks/rocks-5.1/kong/1.4.2-0/kong-1.4.2-0.rockspec` and the entire /usr folder is from kong.tar.gz.

How can I upgrade the plugin version to 0.8.0?

**Comment by Tieske** [comment]
try remove the existing one using luarocks, and installing the newer one (warning: untested!)
```
luarocks remove kong-plugin-prometheus --force
luarocks install <packed_rock_name>.rock
```

**Comment by fighterleslie** [comment]
@Tieske 

Hi, I believe I have solved this problem, below is the instructions in our Dockerfile:

```
RUN sed -i "s/kong-prometheus-plugin ~> 0.6/kong-prometheus-plugin ~> 0.8/g" /usr/local/lib/luarocks/rocks-5.1/kong/1.4.2-0/kong-1.4.2-0.rockspec
RUN apk add --no-cache git
RUN luarocks install kong-prometheus-plugin 0.8.0
```

you will need git because `luarocks install` use `git checkout` internally

**Comment by Tieske** [comment]
Thnx for the solution @fighterleslie
