### ISSUE TITLE
transparent setting on KONG_PROXY_LISTEN fails

### ISSUE THREAD

**Issue by David-Lor** [Kong/docker-kong#363]
According to Kong documentation, the tag "transparent" can be set on KONG_PROXY_LISTEN ports. However, on Docker image, this makes the container to fail on startup while parsing the env variable.

Setting `KONG_PROXY_LISTEN=0.0.0.0:8000 transparent` will make the container fail with the message:

```
  Run with --v (verbose) or --vv (debug) for more details,
Error: proxy_listen must be of form: [off] | <ip>:<port> [ssl] [http2] [proxy_protocol] [deferred] [bind] [reuseport] [backlog=%d+], [... next entry ...]
```

**Comment by hutchic** [comment]
`transparent` proxying was removed as of `2.0`

**Comment by David-Lor** [comment]
I saw it on 2.0.x documentation, which I forget to link on the original post :speak_no_evil: https://docs.konghq.com/2.0.x/network/#transparent-proxying

**Comment by hutchic** [comment]
That explains it ;) . Looks like that page needs updating sincerely sorry for that.

https://docs.konghq.com/2.0.x/configuration/ looks more current
