### ISSUE TITLE
Docker image support for aarch64 (Arm64)

### ISSUE THREAD

**Issue by jsrz** [Kong/docker-kong#395]
I'd like to request support for an Arm based docker image.

I tried running the Docker install instructions here:
https://docs.konghq.com/install/docker/

When I run step 3 (or 4) I'm met with a message that say's there is not Arm support for this image.

`docker run --rm \
>      --network=kong-net \
>      -e "KONG_DATABASE=postgres" \
>      -e "KONG_PG_HOST=kong-database" \
>      -e "KONG_PG_USER=kong" \
>      -e "KONG_PG_PASSWORD=kong" \
>      -e "KONG_CASSANDRA_CONTACT_POINTS=kong-database" \
>      kong:latest kong migrations bootstrap
Unable to find image 'kong:latest' locally
latest: Pulling from library/kong
docker: no matching manifest for linux/arm64/v8 in the manifest list entries.
See 'docker run --help'.`

**Comment by hutchic** [comment]
At this time the arm64 images are tagged `kong:ubuntu`
