### ISSUE TITLE
why we need kong-migrations and kong-migrations-up in docker-compose file

### ISSUE THREAD

**Issue by ChenZhaobin** [Kong/docker-kong#410]
Hey,could some one explain this to me please? why in the docker-compose file,despite the service kong,there are also two other same service kong-migrations and kong-migrations-up?
what's the relation between them, what's the mechanism of this ?or should I say how it works when we deploy using this docker-composer file?

**Comment by Tieske** [comment]
these are base steps in the Kong setup; see https://docs.konghq.com/install/docker/
