### ISSUE TITLE
use BOTH local rock server and luarocks.org when ROCKS_DIR is used ?

### ISSUE THREAD

**Issue by crypto-3dd13** [Kong/docker-kong#419]
when `ROCKS_DIR` is specified during `docker build`, only local rocks is considered because the usage of `--only-server` at 
https://github.com/Kong/docker-kong/blob/master/customize/packer.lua#L294

would it be better that `--server` is used instead, so the packer can support both local custom plugin and also public luarocks plugin ?

**Comment by Tieske** [comment]
the reasoning behind that feature is that some clients cannot use public code, everything must be curated. So it must be limited to only the specific server, and never fallback on a public one.

If you need a mix of both public and private modules, then you can first add the public ones in a first run to create an intermediate image, then run again with that image as input and use the local rockserver only to add the private ones.

Alternatively download the required public rocks into you private one, and run with private only.

**Comment by crypto-3dd13** [comment]
thanks for the clarification
