### ISSUE TITLE
How to use --nginx-conf to load custom nginx template file?

### ISSUE THREAD

**Issue by stefli** [Kong/docker-kong#426]
We use the customize function by using --build-arg to add a custom Nginx template file to the image with kong 2.1.3.
`docker build . \                                                   
    --tag "kong:2.1.3.1" \                             
    --build-arg TEMPLATE="custom_nginx.template"`

But it doesn't work, it always used the default nginx.conf to start the kong. After executing the "kong reload --nginx-conf /custom_nginx.conf", the nginx.conf would be replaced by the template.

We also tried to use ConfigMap to override the nginx.conf file under the folder /usr/local/kong, but failed with exception "/usr/local/kong" Read-only file system.

Any help pls? How to make the arg --nginx-conf works?

**Comment by Tieske** [comment]
you shouldn't have to specify the template. It gets installed in the filesystem if available (https://github.com/Kong/docker-kong/blob/master/customize/packer.lua#L412), but also added to the new entrypoint such that it will be used at startup, see https://github.com/Kong/docker-kong/blob/master/customize/packer.lua#L383-L384

**Comment by Tieske** [comment]
here's the test code; https://github.com/Kong/docker-kong/blob/master/tests/02-customize.test.sh#L133-L134 maybe that sheds some light?

**Comment by stefli** [comment]
> you shouldn't have to specify the template. It gets installed in the filesystem if available (https://github.com/Kong/docker-kong/blob/master/customize/packer.lua#L412), but also added to the new entrypoint such that it will be used at startup, see https://github.com/Kong/docker-kong/blob/master/customize/packer.lua#L383-L384

@Tieske Tie 
I have tried this solution, but it doesn't work. The `/usr/local/kong/nginx.conf` is still the default configuration which should be replaced by /custom_nginx.conf。

Now, I use configmap to override the `/usr/local/kong/nginx.conf` file。Due to the wrong configuration, I got "Read-only file system" before, now it's fixed.

**Comment by stefli** [comment]
According to the lines:
`
# prefix the custom template option, since the last one on the command line
# wins, so the user can still override this template
INITIAL="$1 $2"
if [ -f /custom_nginx.conf ]; then
  # only for these commands support "--nginx-conf"
  echo 1: $INITIAL
  if [ "$INITIAL" = "kong prepare" ] || \
     [ "$INITIAL" = "kong reload"  ] || \
     [ "$INITIAL" = "kong restart" ] || \
     [ "$INITIAL" = "kong start"   ] ; then
    INITIAL="$1 $2 --nginx-conf=/custom_nginx.conf"
  fi
fi
# shift 1 by 1; if there is only 1 arg, then "shift 2" fails
if [ ! "$1" = "" ]; then
  shift
fi
if [ ! "$1" = "" ]; then
  shift
fi

exec /old-entrypoint.sh $INITIAL "$@"
`
We need to run `kong prepare/reload/start/restart` to  add argument "INITIAL="$1 $2 --nginx-conf=/custom_nginx.conf" to make template work. But only the command `kong docker-start` in the old-entrypoint.sh can start kong successfully in docker(k8s).
If we change to use `kong start`, the docker container will fail even the log shows that `Kong started`.

**Comment by Tieske** [comment]
glad it worked out! thx for reporting back 👍
