### ISSUE TITLE
[Question] Why both: kong-migrations and kong-migrations-up?

### ISSUE THREAD

**Issue by x80486** [Kong/docker-kong#429]
According to the [official documentation](https://docs.konghq.com/install/docker/#with-a-database), any recent version of Kong would only need: `kong migrations bootstrap`:

> with Kong versions below 0.15 (up to 0.14), use the up sub-command instead of bootstrap

So I was wondering why would you have those two service definitions in the `docker-compose.yml` file?

I can only think to support any version, but if that would be the case, does running `kong migrations up && kong migrations finish` and/or `kong migrations bootstrap` indistinctly could cause any side effects? Moreover, if I'm sure I'm running Kong `2.1` is it (more than) OK to not have the `kong-migrations-up` definition?

Thanks in advance! :sunglasses:

**Comment by Tieske** [comment]
upgrades.

`bootstrap` is for bootstrapping the database the first time. Use this if you have no existing config in the DB yet.

`up` and `finish` is for upgrading an existing database. Use this if your are replacing a Kong version with a newer one, while retaining the configuration in the database.
