### ISSUE TITLE
kong:2.3.0-alpine failed to load go plugin

### ISSUE THREAD

**Issue by westwin** [Kong/docker-kong#445]
I just tried to upgrade kong from kong:2.2.1-alpine to very latest 2.3.0, but it failed to load go plugin, which works great in 2.2.1.

the go plugin dir is defined as  -e "KONG_GO_PLUGINS_DIR=/home/kong/go-plugins".

Is there any chance this is a bug in 2.3.0 ?

thanks

**Comment by javierguerragiraldez** [comment]
thanks for the report!  

much of this code has changed in 2.3, because we want to support multiple languages, but Kong should detect when you're using the Golang style configuration and adapt accordingly.  We also added visibility via log messages on the whole process.   can you check the logs to see where it failed?

**Comment by westwin** [comment]
kong keeps restarting, with below logs(the golang plugin name here is "iag")

2021/01/14 03:27:54 [error] 1#0: init_by_lua error: /usr/local/share/lua/5.1/kong/init.lua:489: error loading plugin schemas: on plugin 'iag': iag plugin is enabled but not installed;
no plugin found
stack traceback:
	[C]: in function 'assert'
	/usr/local/share/lua/5.1/kong/init.lua:489: in function 'init'
	init_by_lua:3: in main chunk

**Comment by javierguerragiraldez** [comment]
seems like the go-pluginserver doesn't load your plugin.  have you compiled both the plugin and pluginserver recently?  i usually do both any time i have to do either.  it's the easiest way to be sure they're using the exact same version of the compiler and libraries.

**Comment by westwin** [comment]
Yes. I've compiled both the plugin and pluginserver with same go version. 

The only difference is that the built-in plugin server with kong is built with go 1.13, but I rebuilt both the plugin and plugin-server with go 1.14(I did the same thing with kong 2.2.1)

**Comment by javierguerragiraldez** [comment]
I can't reproduce your issue.  It still seems like Kong isn't running the go-pluginserver to ask for your plugin.

Your setup should work as expected, unless something else is wrong, like the exact path to the pluginserver (the default is `/usr/loca/bin`) or something like that.   Also note that Kong 2.3.0 allows for a different kind of configuration, but detects when you're using the old one and adapts accordingly.  Under the new style, you can now compile your plugin as a standalone executable and no longer use the go-pluginserver.  The documentation explaining all this will be posted soon.

**Comment by westwin** [comment]
> I can't reproduce your issue. It still seems like Kong isn't running the go-pluginserver to ask for your plugin.
> 
> Your setup should work as expected, unless something else is wrong, like the exact path to the pluginserver (the default is `/usr/loca/bin`) or something like that. Also note that Kong 2.3.0 allows for a different kind of configuration, but detects when you're using the old one and adapts accordingly. Under the new style, you can now compile your plugin as a standalone executable and no longer use the go-pluginserver. The documentation explaining all this will be posted soon.

I confirm  the embedded standalone process works (alpine-2.3.1)

Thanks

**Comment by javierguerragiraldez** [comment]
Great news, thank for the letting us know.

Just to confirm, you were running kong and the go-pluginserver in an alpine container?  maybe you compiled both under a non-alpine system?  If so, that could've been the problem: dynamically-linked Go programs are not so self-contained as other "normal" Go programs.  In particular, Alpine Linux uses musl instead of glibc,  That's one of the (many) reasons for the new standalone plugin option: they become "normal" Go executables, with all the portability Go developers expect.

**Comment by westwin** [comment]
> Great news, thank for the letting us know.
> 
> Just to confirm, you were running kong and the go-pluginserver in an alpine container? maybe you compiled both under a non-alpine system? If so, that could've been the problem: dynamically-linked Go programs are not so self-contained as other "normal" Go programs. In particular, Alpine Linux uses musl instead of glibc, That's one of the (many) reasons for the new standalone plugin option: they become "normal" Go executables, with all the portability Go developers expect.

Yes, in 2.2.x, both the plugin .so and kong/go-pluginserver is a alpine version
