### ISSUE TITLE
Compile go-pluginserver with docker 

### ISSUE THREAD

**Issue by ealogar** [Kong/docker-kong#458]
When we follow the kong guidelines for building kong with go support (using the alpine-docker image) we found that we can not build the go-plugin server and our kong image (with go support) fails, affecting our images

I just opened this issue https://github.com/Kong/go-pdk/issues/62 as a change in go-pdk broke the go-pluginserver last night.

As the go-pluginserver is part of the kong ecosystem, It would be nice that it were compiled and distributed with the kong docker images.

This is the dockerfile we have developed for doing this (maybe you can do something similar):

```
FROM golang:1.13.14-alpine3.11 as compiler

# Install dependencies for installing custom plugins (needs compilation)
RUN apk add --no-cache build-base libgcc make bash git

# Follow kong compile guide as go dependencies with mod is a hell
RUN go get github.com/Kong/go-pluginserver

# Workaround for the issue https://github.com/golang/go/issues/31354
# following https://github.com/Kong/docker-kong/issues/326
# as we dont use go.mod from now, this is not a problem
COPY apigw/kong/go-plugins /tmp/go-plugins
RUN go get gopkg.in/square/go-jose.v2
RUN cd /tmp/go-plugins; go build -buildmode plugin jwe.go

FROM kong:2.0.4-alpine
...
# Copy Go files
COPY --from=compiler /tmp/go-plugins/*.so /usr/local/go-plugins/
RUN chmod -R 755 /usr/local/go-plugins/*.so

# Replace Go Plugin Server executable (kong is sensitive with comppiler versions)
COPY --from=compiler /go/bin/go-pluginserver /usr/local/bin/go-pluginserver
#COPY --from=compiler /go/src/app/go-pluginserver/go-pluginserver /usr/local/bin/go-pluginserver
RUN chmod -R 755 /usr/local/bin/go-pluginserver
...

```

**Comment by fffonion** [comment]
Hi @ealogar , `go get` outside a go mod directory ignores the go.mod of the installed module, as the link to go issues
stated inside the dockerfile. So it always find the master branch if it's a git repository.
Though go-pdk has changed the API and go-pluginserver is lagging behind, generally you should honor
the go.mod defined in the module you are installing. As we follow semantic versioning in both repos, there
could always be breaking change introduced. It's dangerous to a introduce potentially imcompatible dependency.

So the solution will be to tell `go get` to honor the go.mod here:

`RUN GO111MODULE=on go get github.com/Kong/go-pluginserver`

This will also get rid of the `RUN go get gopkg.in/square/go-jose.v2` later.

I will open a PR to update our doc. I will leave to @javierguerragiraldez about the plan for newer version
of go-pluginserver. You will probably also want to take a look on using the [embedded server](https://docs.konghq.com/gateway-oss/2.3.x/external-plugins/#embedded-server) btw, it will give you
better management of dependencies.

**Comment by ealogar** [comment]
thanks @fffonion , I will check your proposal

**Comment by javierguerragiraldez** [comment]
HI @ealogar 

It seems your issue comes from go-pdk v0.7.0-beta1, since go-pluginserver does **not** work with it.  Please check which version you have.

I concur with @fffonion in that you _need_ to use Go modules.  In particular, modules won't pull any "prerelease" version unless specifically asked.

I've just verified that on a clean Alpine Linux container `go get github.com/Kong/go-pluginserver` pulls go-pdk v0.7.0-beta1 (and fails to compile), while `GO111MODULE=on go get github.com/Kong/go-pluginserver` uses go-pdk v0.6.1

Finally, we do suggest to use the embedded server, as it follows the "normal" (and better supported) style of statically-linked executables; avoiding a lot of interdependencies issues between go-pluginserver and plugins (which is why we can't ship a compiled go-pluginserver)

**Comment by ealogar** [comment]
Thanks @fffonion and @javierguerragiraldez 

I have been testing the use of GO111MODULE with success. Before I just export the environment variable and this was not working but launching in the same go get module seems to work.
I have also changed my go plugin to use go.mod and sum

In future I will change to kong 2.3 (now we are in 2.0.4) and use emebedded server ...

**Comment by ealogar** [comment]
Feel free to close this, the embedded server is the way to do this as you suggest

**Comment by gszr** [comment]
Closing this. Thanks for reporting, @ealogar.
