### ISSUE TITLE
Bintray images will be deprecated and throwing 403

### ISSUE THREAD

**Issue by onfla11** [Kong/docker-kong#460]
Attention: All Bintray services will be deprecated and your accounts will be disabled on May 1st 2021. 

` curl -fL https://bintray.com/kong/kong-deb/download_file?file_path=kong-${KONG_VERSION}.xenial.$(dpkg --print-architecture).deb -o /tmp/kong.deb`

The requested URL returned error: 403 Forbidden

What are the plans to resolve this issue? Thanks.

**Comment by gszr** [comment]
Dockerfiles are up to date with new download location. Thanks for taking the time to report this, @onfla11!
