### ISSUE TITLE
[RFE] Add support for base64 encoded KONG_LICENSE_DATA string

### ISSUE THREAD

**Issue by usrbinkat** [Kong/docker-kong#468]
Issue: 
When writing IaC in a mix of HCL and json, passing license into container via environment variable can become problematic due to complexities of nested json.

Proposal:
Add conditional base64 encoded license ternary check to container entrypoint to decode license data string if found.

**Comment by mflendrich** [comment]
@usrbinkat why was that added to the Team Kubernetes board? I assume it was a misclick - please correct me otherwise.

**Comment by usrbinkat** [comment]
I do not believe I've been in the Team Kubernetes board so I am unsure.

Closing for now
