### ISSUE TITLE
url lose efficacy

### ISSUE THREAD

**Issue by ancienter** [Kong/docker-kong#489]
i try to build from tag 1.5.1，but the url in alpine/Dockerfile is lose efficacy。
the url is "https://bintray.com/kong/kong-alpine-tar/download_file?file_path=kong-$KONG_VERSION.amd64.apk.tar.gz"

**Comment by gszr** [comment]
Hi @ancienter. We no longer maintain Kong 1.5. I would recommend you to switch to a newer version (latest is 2.5, check it out! :). Our new download location is download.konghq.com.
