### ISSUE TITLE
No up-to-date versions on registry.connect.redhat.com?

### ISSUE THREAD

**Issue by sfhardman** [Kong/docker-kong#501]
The latest tag showing at the [Redhat registry](https://catalog.redhat.com/software/containers/kong/kong/5bd44e6269aea375267725e2?container-tabs=gti) is 2.4.0.  The [search results](https://catalog.redhat.com/software/containers/search?q=kong&p=1) show last update as 7 days ago - I wonder if tagging is broken?

**Comment by sfhardman** [comment]
There is a fix PR in #499

**Comment by gszr** [comment]
Hi @sfhardman,

Thanks for bringing this to our attention. We will investigate and report back soon.

Cheers!

**Comment by sfhardman** [comment]
Any update on this please? The latest release available on RH containers is 2.5.1

**Comment by gszr** [comment]
Hi @sfhardman we will look into this. Thanks for reporting!

**Comment by curiositycasualty** [comment]
https://catalog.redhat.com/software/containers/5bd44e6269aea375267725e2?architecture=amd64&tag=2.8.1
