### ISSUE TITLE
Docker Compose examples have become outdated and aren't working for the Kong scale example

### ISSUE THREAD

**Issue by jf-delineate** [Kong/docker-kong#521]
The current existing Docker Compose examples have become outdated, not working in all cases and the documentation could be a bit clearer. Some examples of this:

* The commands in the `readme` are deprecated for the newer version on Compose
* The example of scaling Kong fails due to port/hostname clashes (see below)
* There is no reference to the purpose  of the `makefile` in relation to the examples

I'm happy to create a PR to address these issues and add some tests run through GitHub Actions to validate these changes are working as expected. 

<details>
  <summary>Scale Output</summary>
❯ docker-compose scale kong=3

WARNING: The scale command is deprecated. Use the up command with the --scale flag instead.
WARNING: The "kong" service specifies a port on the host. If multiple containers for this service are created on a single host, the port will clash.
Creating compose_kong_2 ... 
Creating compose_kong_2 ... error
WARNING: Host is already in use by another container
Creating compose_kong_3 ... error

ERROR: for compose_kong_2  Cannot start service kong: driver failed programming external connectivity on endpoint compose_kong_2 (816bf73d7e750bb2705934672bb256a1b0fca62e47e6a1874dae610b2ee4ac41): Bind for 127.0.0.1:8444 failed: port is already allocated

ERROR: for compose_kong_3  Cannot start service kong: driver failed programming external connectivity on endpoint compose_kong_3 (24ce3ff1b6b61e21e5182b99db12ed760350892ccec63e1155e7bfe143dc83a8): Bind for 127.0.0.1:8444 failed: port is already allocated
ERROR: Cannot start service kong: driver failed programming external connectivity on endpoint compose_kong_2 (816bf73d7e750bb2705934672bb256a1b0fca62e47e6a1874dae610b2ee4ac41): Bind for 127.0.0.1:8444 failed: port is already allocated
</details>

**Comment by gszr** [comment]
Hi @jf-delineate,

> I'm happy to create a PR to address these issues and add some tests run through GitHub Actions to validate these changes are working as expected.

Thank you for reporting this. PRs are most welcome!

**Comment by jfnw-capco** [comment]
@gszr would it be possible to get a review of PR #533?  Happy to receive any feedback of course.  I believe this closes 3 open issues (although I couldn't associate them to the PR) but it's pending approvals of the workflow, this is a change is isolated to docker-compose.

**Comment by gszr** [comment]
All, as this is not currently in our plans, I will close this issue out. We have adjusted the Compose README to remove stale mentions of Swarm. https://github.com/Kong/docker-kong/pull/628. If Swarm support is still important to you, I encourage you to create a new issue, as a feature request.
