### ISSUE TITLE
Why does Kong consume so much memory? 

### ISSUE THREAD

**Issue by masksshow** [Kong/docker-kong#536]
FROM kong:2.6.0
----
I read the documentation, the cong is based on Nginx.
I set nginx_worker_processes = 1
My Nginx container consumes 3 mb. Kong consumes 115mb
What is wrong with it?

I have read all the documentation. It doesn't say a word about how much memory Kong consumes.
I have changed all configurations to the minimum. But it had no effect.
Why kong uses more than 100mb. Is this the norm?

**Comment by locao** [comment]
Hi @masksshow!

Kong is actually based on [OpenResty](https://github.com/openresty/openresty) which has much more functionality than a basic Nginx installation. For starters, OpenResty needs a lua interpreter to execute and Kong is full gateway over this, so they cannot be compared.

If you need some advice on resource allocation for Kong, you can read about it [here](https://docs.konghq.com/gateway/2.7.x/plan-and-deploy/sizing-guidelines/).
