### ISSUE TITLE
`docker-compose up`: ERROR: Version in "./docker-compose.yml" is unsupported

### ISSUE THREAD

**Issue by mpuels** [Kong/docker-kong#540]
Running

```
docker-compose up
```

in https://github.com/Kong/docker-kong/tree/master/compose exits with this error (linebreaks added by me):

```
ERROR: Version in "./docker-compose.yml" is unsupported. You might be seeing this error 
because you're using the wrong Compose file version. Either specify a supported version (e.g 
"2.2" or "3.3") and place your service definitions under the `services` key, or omit the `version` 
key and place your service definitions at the root of the file to use version 1.

For more on the Compose file format versions, see https://docs.docker.com/compose/compose-file/
```
The `version` 3.9 in

https://github.com/Kong/docker-kong/blob/6c67c804164cc9dd43b9f91b4cdc694e8773c6f1/compose/docker-compose.yml#L1

doesn't even exist in the official Docker documentation:

![Screenshot from 2022-02-02 18-53-54](https://user-images.githubusercontent.com/2924816/152210115-a0c99dfd-f2d3-43f8-869f-a7c3de513b4d.png)

https://docs.docker.com/compose/compose-file/#compose-and-docker-compatibility-matrix

Probably I'm missing a fundamental thing. I'd be happy to know why it doesn't work on my machine.

**Comment by jremerich** [comment]
I upgraded my docker-compose following this: https://docs.docker.com/compose/install/

First I removed current binary with `sudo rm -f /usr/local/bin/docker-compose` then followed instructions to a new installation.

**Comment by hutchic** [comment]
@jremerich nailed it.

docker-compose is being remade into a docker cli plugin. We depend on 3.9 and it's use of profiles. I'll adjust the docker-compose README.md to explicitely call out the docker version.

Our docker-compose is mostly backwards and forwards compatible just less feature rich in earlier versions so feel free to jump to a different commit is an option as well

**Comment by Tieske** [comment]
can we close this issue then?

**Comment by mpuels** [comment]
From my point of view this issue can be closed. Unless you want to keep it open until the  docker-compose README.md has been updated as described in

> I'll adjust the docker-compose README.md to explicitely call out the docker version.

in https://github.com/Kong/docker-kong/issues/540#issuecomment-1091688286

**Comment by gszr** [comment]
README change coming in! https://github.com/Kong/docker-kong/pull/628

Thanks all for the discussion!
