### ISSUE TITLE
docker installed kong; The difference between the two paths in the screenshot

### ISSUE THREAD

**Issue by zhouxihua0311** [Kong/docker-kong#542]
![image](https://user-images.githubusercontent.com/39576880/155445868-3515a028-40b2-4fd6-83ee-4318166b18f6.png)

**Comment by gszr** [comment]
Hi there,

I do not understand the issue here (and a `find / -name kong.conf.default` doesn't give me the same result). Please feel free to reopen with more info - what the issue is and how to reproduce.

Thanks!
