### ISSUE TITLE
kong-2.4.0.amd64.apk.tar.gz download 403

### ISSUE THREAD

**Issue by zcong2333** [Kong/docker-kong#543]
curl -fL 'https://bintray.com/kong/kong-alpine-tar/download_file?file_path=kong-2.4.0.amd64.apk.tar.gz'
curl: (22) The requested URL returned error: 403 Forbidden

**Comment by gszr** [comment]
Hi there,

Our new download location is https://download.konghq.com.

Closing this for now.
