### ISSUE TITLE
Unable to access targeted service through docker compose image 

### ISSUE THREAD

**Issue by Jsamal-dev** [Kong/docker-kong#560]
Steps to reproduce issue 

Step 1: git clone git@github.com:Kong/docker-kong.git

Step 2: Go inside 'compose' directory 

Step3: make kong-postgres 

Step 4:  Create service curl -i -X POST http://localhost:8001/services  --data name=example_service  --data url='http://localhost:7070/'

Step 5: Create route curl -i -X POST http://localhost:8001/services/example_service/routes  --data 'paths[]=/mock'  --data name=mocking

Step 6: Hit it from browser with URL http://localhost:8000/mock

Error :

"message":"An invalid response was received from the upstream server"

Log: 

2022/05/16 08:20:35 [error] 1111#0: *43218 connect() failed (111: Connection refused) while connecting to upstream, client: 172.22.0.1, server: kong, request: "GET /moc
k HTTP/1.1", upstream: "http://127.0.0.1:7070/", host: "localhost:8000"
2022/05/16 08:20:35 [error] 1111#0: *43218 connect() failed (111: Connection refused) while connecting to upstream, client: 172.22.0.1, server: kong, request: "GET /moc
k HTTP/1.1", upstream: "http://127.0.0.1:7070/", host: "localhost:8000"
2022/05/16 08:20:35 [error] 1111#0: *43218 connect() failed (111: Connection refused) while connecting to upstream, client: 172.22.0.1, server: kong, request: "GET /moc
k HTTP/1.1", upstream: "http://127.0.0.1:7070/", host: "localhost:8000"
2022/05/16 08:20:35 [error] 1111#0: *43218 connect() failed (111: Connection refused) while connecting to upstream, client: 172.22.0.1, server: kong, request: "GET /moc
k HTTP/1.1", upstream: "http://127.0.0.1:7070/", host: "localhost:8000"
2022/05/16 08:20:35 [error] 1111#0: *43218 connect() failed (111: Connection refused) while connecting to upstream, client: 172.22.0.1, server: kong, request: "GET /moc
k HTTP/1.1", upstream: "http://127.0.0.1:7070/", host: "localhost:8000"
2022/05/16 08:20:35 [error] 1111#0: *43218 connect() failed (111: Connection refused) while connecting to upstream, client: 172.22.0.1, server: kong, request: "GET /moc
k HTTP/1.1", upstream: "http://127.0.0.1:7070/", host: "localhost:8000"
172.22.0.1 - - [16/May/2022:08:20:35 +0000] "GET /mock HTTP/1.1" 502 75 "-" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/100.0.4896.75
 Safari/537.36"

**Comment by gszr** [comment]
Hi @Jsamal-dev,

Note that in step 4 you are adding a service with URL `url='http://localhost:7070/'`. `localhost` in this case refers to the container running Kong, whereas your service lives outside it (in your host machine). Instead of `localhost`, you can pass in the IP address of the container running the service or the container's name, if it's running in the same Docker network as the Kong container. 

Closing this for now.
