### ISSUE TITLE
2.5.1 centos image installing el7 rpm on centos 8

### ISSUE THREAD

**Issue by shuoqingding** [Kong/docker-kong#578]
Hi there, we are planing to use 2.5.1 version of Kong, but I have noticed el7 version of kong rpm is being used in 2.5.1 centos image, and there is actually a 2.5.1 el8 rpm available.
![image](https://user-images.githubusercontent.com/1393690/176873452-261b591c-02e9-424c-82b2-368db4fcda01.png)

So I wanted to check if this is expected and safe to use, thanks!

**Comment by gszr** [comment]
We no longer support a CentOS image. Closing this issue, but feel free to reopen if you need more help.
