### ISSUE TITLE
Trying Docker Compose on MacOS and getting an error db not being used when trying to add a service after running Kong 

### ISSUE THREAD

**Issue by jsdads11** [Kong/docker-kong#580]
curl -i -X POST \
                                              --url http://localhost:8001/services/ \
                                              --data 'name=example-service' \
                                              --data 'url=http://mockbin.org'
HTTP/1.1 405 Not Allowed
Date: Thu, 21 Jul 2022 18:32:18 GMT
Content-Type: application/json; charset=utf-8
Connection: keep-alive
Access-Control-Allow-Origin: *
Content-Length: 114
X-Kong-Admin-Latency: 156
Server: kong/2.8.1

**{"name":"operation unsupported","message":"cannot create 'services' entities when not using a database","code":12}**

**Comment by efburgos** [comment]
Same problem, on docker-compose u can see this ${KONG_DATABASE:-off} u need change this

**Comment by gszr** [comment]
The default is to spin up a db-less Kong -- check [this out](https://docs.konghq.com/gateway/latest/production/deployment-topologies/db-less-and-declarative-config/#main).

If you want to spin up a Kong + Postgres, you can do:
```
  $ KONG_DATABASE=postgres docker-compose --profile database up
```
