### ISSUE TITLE
Image missing for arm64

### ISSUE THREAD

**Issue by aulisius** [Kong/docker-kong#627]
Hi,

I see that `linux/arm64/v8` version image is missing for `kong:2.8.3-alpine`. It's weird because it is available for the non-alpine version.

Could you please rebuild and push the 2.8.3 version for `linux/arm64/v8`?

Thanks.

**Comment by gszr** [comment]
@aulisius,

Thank you for reporting this. We are working on a fix.

**Comment by gszr** [comment]
Hey @aulisius, `docker pull kong:2.8` should now be working as expected (it's alpine based too). The 2.8.3 label hasn't been updated yet, but I am checking on it.

**Comment by gszr** [comment]
Both `2.8.3` and `2.8.3-alpine` for arm64 are back up!
