### ISSUE TITLE
Docker Install link is wrong

### ISSUE THREAD

**Issue by d19dotca** [Kong/docker-kong#658]
Very minor issue, but I couldn't see a way to update it myself. In the Repository Info section, it has the wrong documentation link. It should be https://docs.konghq.com/gateway/latest/install/docker/ and not https://docs.konghq.com/install/docker/. 

<img width="294" alt="image" src="https://github.com/Kong/docker-kong/assets/8153796/dca80fec-348f-4f0f-a2fc-c998bf2bc63e">

**Comment by subnetmarco** [comment]
Updated, thanks.
