### ISSUE TITLE
[Http2]:  docker compose can not enable http2

### ISSUE THREAD

**Issue by GStones** [Kong/docker-kong#676]
## issues
 I have add the  ` KONG_PROXY_LISTEN: '0.0.0.0:8000 http2, 0.0.0.0:8443 ssl http2'`, client still can't connect the 8000 port.
 follow this [doc](https://docs.konghq.com/gateway/latest/production/configuring-a-grpc-service/)

## docker-compose yml
![image](https://github.com/Kong/docker-kong/assets/6346542/e6905386-b5f1-4757-9189-47a34f76483e)

## grpcurl client 
![image](https://github.com/Kong/docker-kong/assets/6346542/58ab6e74-a7cf-4519-8d62-c51a03750bfc)

**Comment by chronolaw** [comment]
Hi @GStones , do you check that the exposed ports of container are correct?

**Comment by GStones** [comment]
Thanks your reply. I already resolved!
