### ISSUE TITLE
Add Headers in Docker Kong

### ISSUE THREAD

**Issue by venkin304** [Kong/docker-kong#693]
I am trying to add HSTS header in the Kong docker-compose.yml file as env variable: 
KONG_NGINX_PROXY_ADD_HEADER: 'Strict-Transport-Security: max-age=31536000'.

But I am getting CORS issue after adding this header. guess this setting is overriding 'Access-Control-Allow-Origin *'.

How can I add multiple headers in my docker-compose.yml file ?

Or is there a better way to add these headers in my dockerised Kong ?

**Comment by gszr** [comment]
Hey @venkin304 

What you intend to do is 
```
KONG_NGINX_PROXY_ADD_HEADER: "Strict-Transport-Security max-age=31536000"
```

From Nginx docs:

> NGINX configuration blocks inherit add_header directives from their enclosing blocks, so you just need to place the add_header directive in the top‑level server block. There’s one important exception: if a block includes an add_header directive itself, it does not inherit headers from enclosing blocks, and you need to redeclare all add_header directives:

If you need to add more headers, I would recommend checking the post-function plugin for example -- see the docs here https://docs.konghq.com/hub/kong-inc/post-function.
