### ISSUE TITLE
Kong Ubuntu base Jammy -> Noble

### ISSUE THREAD

**Issue by jeremyjpj0916** [Kong/docker-kong#725]
https://github.com/Kong/docker-kong/blob/master/ubuntu/Dockerfile#L1 , now that noble is considered the new flagship release, can Kong bump up the OS it builds with in the defacto images? Would you accept a PR to cut over to it? 

We cut over to it in our own docker image build of Kong and things are working great, helps address a few CVEs in jammy that noble has fixed too.

**Comment by locao** [comment]
Fixed by #726. Thank you @jeremyjpj0916! 🎉
