### ISSUE TITLE
Docker-compose up fails because of no Postgress Password.

### ISSUE THREAD

**Issue by echeadle** [Kong/docker-kong#78]
Is there any reason that KONG_PG_PASSWORD is not set as an environment variable under the Kong part of the docker-compose file? 

I've had  a couple of problems getting started.   One was  a kong problem and the other a firewalld problem running on centos 7.  Below are links to resolving the firewalld issue and a pointer to the issue with Kong that led to the resolution.

You might also tell people that the nginx-lb-1 node continues to send log messages to the console. When things are new, it is nice to know what success should look like. This is a very interesting application and as it gets better known, you will start to have less experienced people that are starting out with docker, nginx and your app.  Showing them what they should expect to see after everything is up and running ok would be helpful.

For some reason docker and firewalld do not play nice together. Until there is a fix, this workaround helps.
http://stackoverflow.com/questions/33600154/docker-not-starting-could-not-delete-the-default-bridge-network-network-bridg/33604859#33604859

I tried replicating the password from the Postgres section the the Kong section, that did not work. I stumbled on the following link and it pointed me to the right direction. Essentially the env vars in Kong need to be prefaced by KONG.  

https://github.com/Mashape/kong/blob/master/kong.conf.default#L10-L11

On the kong page: https://getkong.org/install/docker/  you might consider adding a postgress container start block like you do cassandra.  It may not be obvious that you have to pass kong the password in as KONG_PG_PASSWORD.  The default is no password. I am wondering if Postgress changed, like mysql, to not allowing blank passwords.   I had a similar problem trying to use the latest mysql in a class about cloudstack.

Anyway this is a very interesting application. Thanks

**Comment by Tieske** [comment]
fixed long ago
