### ISSUE TITLE
Ability to pass database password via docker secret file

### ISSUE THREAD

**Issue by endeepak** [Kong/docker-kong#91]
[Docker secrets](https://docs.docker.com/engine/swarm/secrets/) allow passing sensitive information via in memory secret files in `/run/secrets/my_secret`. Current kong expects db passwords via env variables like `KONG_PG_PASSWORD` which can't use docker secrets for  secure usage. 

It would be good if kong docker image supports passing db passwords via file. eg: `KONG_PG_PASSWORD_FILE=/run/secrets/kong_pg_password`

**Comment by jalberto** [comment]
Any news about this?

meanwhile I forked and added a workaround: 

https://github.com/jalberto/docker-kong/tree/env-secrets

**Comment by Tieske** [comment]
Only just noticed this issue, because it is on the docker repo, should probably have been on kong itself.

@endeepak @jalberto as a workaround you could use
```shell
export KONG_PG_PASSWORD=$(</run/secrets/kong_pg_password)
kong start
```

other than that, the change to Kong would be fairly trivial, just modify the config parser https://github.com/Mashape/kong/blob/master/kong/conf_loader.lua

So if someone can supply a patch that would be nice ...

**Comment by jalberto** [comment]
my LUA skill is quite limited, here is what would be needed:

- Add `KONG_PG_PASSWORD_FILE` (probably not the only one needed?)
- if `KONG_PG_PASSWORD_FILE` exist read it and set `pg_password` to it's content

Doubts:

- config precedence ?
- bad implications of reading from a file?
- how handle special chars?

**Comment by Tieske** [comment]
Yes, also needed for other secrets like Cassandra password, etc.

>config precedence ?

is handled by the config loader. Only needs some logic to read either the regular password, or the file based on, but never both (should be an error)

> bad implications of reading from a file?

This is being dealt with in the init phase, so not such a pressing issue

>how handle special chars?

Not sure I understand, read the full contents of the file, and that would be the password. No interpretation necessary, right?

**Comment by jalberto** [comment]
> how handle special chars?
> Not sure I understand, read the full contents of the file, and that would be the password. No interpretation necessary, right?

agree, I was thinking more about encoding problems

**Comment by jazztong** [comment]
It is already handled, realize the docker-compose file share here was using docker secret, https://github.com/Kong/docker-kong/tree/master/compose

**Comment by hutchic** [comment]
This has existed in our unofficial docker images as of https://github.com/Kong/docker-kong/pull/348. The unofficial images are available at https://hub.docker.com/repository/docker/kong/kong/tags?page=1 but it's advisable to not use those outside of test / development environments.

The official docker images will have this as of 2.0.4 and I'll probably backport the functionality a few version as well.
